### PR TITLE
Store children in route.__children

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/197)

### CODE REVIEW

**Comment by vlukashov** [comment]
Review status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @SomeoneToIgnore)

---

*[src/router.js, line 169 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/197#-LFXASAb20GekKuvemhu:-LFXASAb20GekKuvemhv:b-q4ltkd) ([raw file](https://github.com/vaadin/vaadin-router/blob/070a77477e11ca99e71ea51c96f1eab8cd3c7f85/src/router.js#L169)):*
> ```JavaScript
>     return callbacks.then(() => runCallbackIfPossible(route.children, undefined, route))
>       .then(newChildren => {
>         route.__children = route.children;
> ```

Let's have only one place where `route.__children` is set based on the `route.children` array. I suggest `matchRoute` for that.

---

*[src/resolver/matchRoute.js, line 75 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/197#-LFXAhUg4u8HMMx_1I8S:-LFXAhUg4u8HMMx_1I8T:ba5ggu3) ([raw file](https://github.com/vaadin/vaadin-router/blob/070a77477e11ca99e71ea51c96f1eab8cd3c7f85/src/resolver/matchRoute.js#L75)):*
> ```JavaScript
>       }
> 
>       const children = route.__children || route.children;
> ```

How about if this would be the only place where `route.__children` is set based on the `route.children` array (if not defined yet)?

---

*[src/resolver/resolver.js, line 62 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/197#-LFXB5qTCkWT0duE_Wm8:-LFXB5qTCkWT0duE_Wm9:b-j7audv) ([raw file](https://github.com/vaadin/vaadin-router/blob/070a77477e11ca99e71ea51c96f1eab8cd3c7f85/src/resolver/resolver.js#L62)):*
> ```
> children: routes,
> ```
Is it necessary to add the `children` property to a synthetic route object?

---

*[src/resolver/resolver.js, line 86 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/197#-LFXBL22DIVDjNO3AYlP:-LFXBL22DIVDjNO3AYlQ:b-a3fiuv) ([raw file](https://github.com/vaadin/vaadin-router/blob/070a77477e11ca99e71ea51c96f1eab8cd3c7f85/src/resolver/resolver.js#L86)):*
> ```
> this.root.children = newRoutes;
> ```
Is it necessary to add the `children` property to a synthetic route object?

---

*[src/resolver/resolver.js, line 102 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/197#-LFXBM3T1UsgUvBsBqqO:-LFXBM3T1UsgUvBsBqqP:b-j3w33f) ([raw file](https://github.com/vaadin/vaadin-router/blob/070a77477e11ca99e71ea51c96f1eab8cd3c7f85/src/resolver/resolver.js#L102)):*
> ```JavaScript
>     ensureRoutes(routes);
>     const newRoutes = [...toArray(routes)];
>     this.root.__children.push(newRoutes);
> ```

`Array.prototype.push()` needs all elements in the array as separate arguments. It should be `this.root.__children.push(...toArray(routes));`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/197)*

**Comment by SomeoneToIgnore** [comment]
Review status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @SomeoneToIgnore and @vlukashov)

---

*[src/resolver/resolver.js, line 62 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/197#-LFXB5qTCkWT0duE_Wm8:-LFXLWRC3SxHweUFt6k_:br0orc2) ([raw file](https://github.com/vaadin/vaadin-router/blob/070a77477e11ca99e71ea51c96f1eab8cd3c7f85/src/resolver/resolver.js#L62)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> children: routes,
> ```
Is it necessary to add the `children` property to a synthetic route object?
</blockquote></details>

`children` is mandatory, `__children` is not, removed that one.

---

*[src/resolver/resolver.js, line 86 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/197#-LFXBL22DIVDjNO3AYlP:-LFXLISw8GWdDl0WQM44:br0orc2) ([raw file](https://github.com/vaadin/vaadin-router/blob/070a77477e11ca99e71ea51c96f1eab8cd3c7f85/src/resolver/resolver.js#L86)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> this.root.children = newRoutes;
> ```
Is it necessary to add the `children` property to a synthetic route object?
</blockquote></details>

`children` is mandatory, `__children` is not, removed that one.

---

*[src/resolver/resolver.js, line 102 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/197#-LFXBM3T1UsgUvBsBqqO:-LFXKu5T-KMTQSUpafBo:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/070a77477e11ca99e71ea51c96f1eab8cd3c7f85/src/resolver/resolver.js#L102)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

`Array.prototype.push()` needs all elements in the array as separate arguments. It should be `this.root.__children.push(...toArray(routes));`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/197)*

**Comment by web-padawan** [comment]
Review status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @SomeoneToIgnore and @vlukashov)

---

*[src/resolver/resolver.js, line 86 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/197#-LFXBL22DIVDjNO3AYlP:-LFXPurvCZzFC9y-ztBH:b-vvdl6m) ([raw file](https://github.com/vaadin/vaadin-router/blob/070a77477e11ca99e71ea51c96f1eab8cd3c7f85/src/resolver/resolver.js#L86)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

`children` is mandatory, `__children` is not, removed that one.
</blockquote></details>

BTW in that case it looks like this method can be left the same as before the PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/197)*

**Comment by vlukashov** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/197)*

**Pull request merged**
