### PR TITLE
Support 'onAfterLeave' callback.

### LINKED ISSUE #166: add an 'onAfterLeave' lifecycle callback
As a developer I want to add custom logic to the point in the view lifecycle when it's certain that a navigation away from that view has just happened (so that I can implement such use cases like counting the time a user has spent on a given view). This is different from the `onBeforeLeave()` lifecycle callback because in `onBeforeLeave()` it is not yet certain whether or not the user will actually navigate away.

DoD:
 - the `onAfterLeave ` callback (if defined) is called before removing the view component from the page DOM (before `disconnectedCallback()`). If the return value is a promise, Vaadin.Router waits until it gets resolved before removing the element from the DOM. Otherwise, any return value is ignored.
 - the `onAfterLeave()` callback is added to `Vaadin.WebComponentInterface`
 - there is a demo of using the `onAfterLeave()` callback (in the Lifecycle Events section)

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Closes #166

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/174)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed, 4 unresolved discussions (waiting on @SomeoneToIgnore)

---

*[demo/vaadin-router-lifecycle-callbacks-demos.html, line 250 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/174#-LFIkcQDBK_M3xZ6WLYR:-LFIkcQDBK_M3xZ6WLYS:b-a1n43c) ([raw file](https://github.com/vaadin/vaadin-router/blob/eb6f209ef53570dafdc9d1115ee82eb5e78290e5/demo/vaadin-router-lifecycle-callbacks-demos.html#L250)):*
> ```HTML
>           router.setRoutes([
>             {path: '/', component: 'x-main-page'},
>             {path: '/editText', component: 'x-autosave-view'},
> ```

let's use lowercase in path values

---

*[demo/vaadin-router-lifecycle-callbacks-demos.html, line 259 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/174#-LFIjrNHEAru-dV-DF-S:-LFIjrNHEAru-dV-DF-T:b-atm0p3) ([raw file](https://github.com/vaadin/vaadin-router/blob/eb6f209ef53570dafdc9d1115ee82eb5e78290e5/demo/vaadin-router-lifecycle-callbacks-demos.html#L259)):*
> ```HTML
>             is: 'x-autosave-view',
>             onBeforeEnter: function() {
>               this.text = savedText;
> ```

let's change this to avoid using Polymer data bindings at least here, e. g.
 ```
this.shadowRoot.querySelector('textarea').value = savedText;
```
and for saving, respectively:
 ```
savedText = this.shadowRoot.querySelector('textarea').value;
```

---

*[demo/vaadin-router-lifecycle-callbacks-demos.html, line 274 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/174#-LFIjTsk7G6yMlTsuiCx:-LFIjTsk7G6yMlTsuiCy:beicvct) ([raw file](https://github.com/vaadin/vaadin-router/blob/eb6f209ef53570dafdc9d1115ee82eb5e78290e5/demo/vaadin-router-lifecycle-callbacks-demos.html#L274)):*
> ```HTML
>         <dom-module id="x-autosave-view">
>           <template>
>             <div><textarea rows=5 cols=30>{{text}}</textarea></div>
> ```

please use double quotes for HTML attributes.

---

*[src/documentation/web-component-interface.js, line 51 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/174#-LFImL7a6Kxix7aYaUWU:-LFIlFkL-lNR1mMFpk7S:b-vg7jk4) ([raw file](https://github.com/vaadin/vaadin-router/blob/eb6f209ef53570dafdc9d1115ee82eb5e78290e5/src/documentation/web-component-interface.js#L51)):*
> ```JavaScript
>  * Any of the `onBefore...` callbacks have a possibility to cancel the navigation and fall back
>  * to the previous navigation result (if there is no result and this is the first resolution, an exception is thrown).
>  * Any of the `onAfter...` value is ignored.
> ```

consider making this a bit longer, e. g. " Any of the `onAfter...` callbacks are considered and non-cancellable, and their return value is ignored. "

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/174)*

**Comment by SomeoneToIgnore** [comment]
Review status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @web-padawan and @SomeoneToIgnore)

---

*[demo/vaadin-router-lifecycle-callbacks-demos.html, line 250 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/174#-LFIkcQDBK_M3xZ6WLYR:-LFJH8MHDPoCAawe983r:b2nhll9) ([raw file](https://github.com/vaadin/vaadin-router/blob/eb6f209ef53570dafdc9d1115ee82eb5e78290e5/demo/vaadin-router-lifecycle-callbacks-demos.html#L250)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

let's use lowercase in path values
</blockquote></details>

Ok.

---

*[demo/vaadin-router-lifecycle-callbacks-demos.html, line 259 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/174#-LFIjrNHEAru-dV-DF-S:-LFJHDT-A1W9wsniAFJL:brg9810) ([raw file](https://github.com/vaadin/vaadin-router/blob/eb6f209ef53570dafdc9d1115ee82eb5e78290e5/demo/vaadin-router-lifecycle-callbacks-demos.html#L259)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

let's change this to avoid using Polymer data bindings at least here, e. g.
 ```
this.shadowRoot.querySelector('textarea').value = savedText;
```
and for saving, respectively:
 ```
savedText = this.shadowRoot.querySelector('textarea').value;
```

</blockquote></details>

Right, more standardized, thanks.

---

*[demo/vaadin-router-lifecycle-callbacks-demos.html, line 274 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/174#-LFIjTsk7G6yMlTsuiCx:-LFJHXjE-TC_27KFLp9u:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/eb6f209ef53570dafdc9d1115ee82eb5e78290e5/demo/vaadin-router-lifecycle-callbacks-demos.html#L274)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

please use double quotes for HTML attributes.
</blockquote></details>

Done.

---

*[src/documentation/web-component-interface.js, line 51 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/174#-LFImL7a6Kxix7aYaUWU:-LFJHxys7r5YsFBEB6VT:b2nhll9) ([raw file](https://github.com/vaadin/vaadin-router/blob/eb6f209ef53570dafdc9d1115ee82eb5e78290e5/src/documentation/web-component-interface.js#L51)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

consider making this a bit longer, e. g. " Any of the `onAfter...` callbacks are considered and non-cancellable, and their return value is ignored. "
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/174)*

**Comment by SomeoneToIgnore** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[demo/vaadin-router-lifecycle-callbacks-demos.html, line 250 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/174#-LFIkcQDBK_M3xZ6WLYR:-LFJgaWyEEUBO7yVpIAv:b-dr8uc7) ([raw file](https://github.com/vaadin/vaadin-router/blob/eb6f209ef53570dafdc9d1115ee82eb5e78290e5/demo/vaadin-router-lifecycle-callbacks-demos.html#L250)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

maybe just "edit"?
</blockquote></details>

Yeah, looks better, thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/174)*

**Comment by vlukashov** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed, 1 unresolved discussion (waiting on @SomeoneToIgnore)

---

*[test/router/lifecycle-events.spec.html, line 51 at r4](https://reviewable.io/reviews/vaadin/vaadin-router/174#-LFLi4BN1BFW8uD7D3KR:-LFLi4BO8whIaFo0h7VX:b15o2x3) ([raw file](https://github.com/vaadin/vaadin-router/blob/b90b1a3210af891f3fc1c5cd1e1703f0811c7bc3/test/router/lifecycle-events.spec.html#L51)):*
> ```HTML
> 
>     describe('Vaadin.Router lifecycle events', function() {
>       const {verifyActiveRoutes, onAfterEnterAction, onAfterLeaveAction, onBeforeEnterAction, onBeforeLeaveAction} = VaadinTestNamespace;
> ```

nit: the line seems to be too long
Please consider wrapping it. An idiomatic way would be

```
const {
  verifyActiveRoutes,
  onAfterEnterAction,
  onAfterLeaveAction,
  onBeforeEnterAction,
  onBeforeLeaveAction
} = VaadinTestNamespace;
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/174#-:-LFLjSsz7-jv6mXSH3ZZ:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @SomeoneToIgnore)

---

*[test/router/lifecycle-events.spec.html, line 51 at r4](https://reviewable.io/reviews/vaadin/vaadin-router/174#-LFLi4BN1BFW8uD7D3KR:-LFLmAuc5p7kzLOMOEJ7:bfkmkxz) ([raw file](https://github.com/vaadin/vaadin-router/blob/b90b1a3210af891f3fc1c5cd1e1703f0811c7bc3/test/router/lifecycle-events.spec.html#L51)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

nit: the line seems to be too long
Please consider wrapping it. An idiomatic way would be

```
const {
  verifyActiveRoutes,
  onAfterEnterAction,
  onAfterLeaveAction,
  onBeforeEnterAction,
  onBeforeLeaveAction
} = VaadinTestNamespace;
```
</blockquote></details>

Linter was not complaining, but sure, done :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/174)*

**Comment by vlukashov** [comment]
Reviewed 2 of 2 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/174)*

**Pull request merged**
