### PR TITLE
Add convenience methods to context object.

### LINKED ISSUE #125: When defining custom action for the route, I would like to have a shortcut methods in context
Currently it's rather cumbersome to make the router display some particular route as an action result:

* for redirect, I need to return something like `return {redirect: {pathname: '/c', from: '/a/b'}};`
* for rendering a custom component I need to call something like `Vaadin.Router.renderComponent('x-home-view', context)`

It might make sense to create a methods that will do the same but internally and put them into context.
Proposed names:
* for redirect, `context.redirect(toPath: String)`
* for rendering, `context.render(webComponentId: String)`

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Closes #125

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/129)

### CODE REVIEW

**Comment by vlukashov** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---

*[demo/vaadin-router-route-actions-demos.html, line 38 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDpwZ3T2RIBw65W_GkN:-LDpwZ3T2RIBw65W_GkO:b-ev1p7h) ([raw file](https://github.com/vaadin/vaadin-router/blob/a6f10598cdae26d990bbcec9bad54550bbc4a760/demo/vaadin-router-route-actions-demos.html#L38)):*
> ```HTML
>         <li><code>context.next</code> [function] proceed to resolving the next
>           matching route (if any)</li>
>         <li><code>context.redirect(path)</code> [function] redirect to the path specified</li>
> ```

Let's emphasize that only calling the `context.redirect()` function would not redirect anywhere, and that redirect happens only if the return value from the `context.redirect()` function is returned as the action 'result'.

---

*[demo/vaadin-router-route-actions-demos.html, line 39 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDpxTaQ4NA5-0emo42K:-LDpxTaQ4NA5-0emo42L:brkargg) ([raw file](https://github.com/vaadin/vaadin-router/blob/a6f10598cdae26d990bbcec9bad54550bbc4a760/demo/vaadin-router-route-actions-demos.html#L39)):*
> ```HTML
>           matching route (if any)</li>
>         <li><code>context.redirect(path)</code> [function] redirect to the path specified</li>
>         <li><code>context.render(component)</code> [function] that calls
> ```

How about renaming the `render` method to `component` so that the it matches the route property name?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/129)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/vaadin-router-route-actions-demos.html, line 151 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDpxyou-p80PToIeYbW:-LDpxyou-p80PToIeYbX:b-2bthi2) ([raw file](https://github.com/vaadin/vaadin-router/blob/a6f10598cdae26d990bbcec9bad54550bbc4a760/demo/vaadin-router-route-actions-demos.html#L151)):*
> ```HTML
>     </vaadin-demo-snippet>
> 
>     <h3>Redirecting from an action</h3>
> ```

let's capitalise this: "Redirecting from an Action"

---

*[demo/vaadin-router-route-actions-demos.html, line 162 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDpyMDp-n0MPqBdBKW8:-LDpyMDp-n0MPqBdBKW9:b-h4leg3) ([raw file](https://github.com/vaadin/vaadin-router/blob/a6f10598cdae26d990bbcec9bad54550bbc4a760/demo/vaadin-router-route-actions-demos.html#L162)):*
> ```HTML
>     <p>
>       Note: If you need only to redirect to another route, defining an action might be an overkill.
>       More convenient way is described in <a href="#vaadin-router-redirect-demos">Router redirect</a> section.
> ```

let's change "Router redirect" to "Redirects" so that the link text is consistent with the navigation

---

*[demo/vaadin-router-route-actions-demos.html, line 192 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDpy5Kr07ba61GgM3Dp:-LDpy5Kr07ba61GgM3Dq:b9ucm3a) ([raw file](https://github.com/vaadin/vaadin-router/blob/a6f10598cdae26d990bbcec9bad54550bbc4a760/demo/vaadin-router-route-actions-demos.html#L192)):*
> ```HTML
>     </vaadin-demo-snippet>
> 
>     <h3>Returning custom element as an action result</h3>
> ```

let's capitalise this: "Returning Custom Element as an Action Result"

---

*[demo/vaadin-router-route-actions-demos.html, line 201 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDpyenXCRKYfDJ4Lhcr:-LDpyenXCRKYfDJ4Lhcs:b4iuqnx) ([raw file](https://github.com/vaadin/vaadin-router/blob/a6f10598cdae26d990bbcec9bad54550bbc4a760/demo/vaadin-router-route-actions-demos.html#L201)):*
> ```HTML
>       Note: If the only thing your action does is custom element creation, it can
>       be replaced with <code>component</code> property of the route.
>       See <a href="#vaadin-router-basic-demos">Basic demos</a> section for examples.
> ```

"Basic demos" is now called "Getting Started"

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/129)*

**Comment by SomeoneToIgnore** [comment]
Review status: 5 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[demo/vaadin-router-route-actions-demos.html, line 38 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDpwZ3T2RIBw65W_GkN:-LDpyJd-6seCWFI_O4B6:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/a6f10598cdae26d990bbcec9bad54550bbc4a760/demo/vaadin-router-route-actions-demos.html#L38)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Let's emphasize that only calling the `context.redirect()` function would not redirect anywhere, and that redirect happens only if the return value from the `context.redirect()` function is returned as the action 'result'.
</blockquote></details>

Done.

---

*[demo/vaadin-router-route-actions-demos.html, line 39 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDpxTaQ4NA5-0emo42K:-LDpyJwCC0YZADxtnb8O:b-v7hq0s) ([raw file](https://github.com/vaadin/vaadin-router/blob/a6f10598cdae26d990bbcec9bad54550bbc4a760/demo/vaadin-router-route-actions-demos.html#L39)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

How about renaming the `render` method to `component` so that the it matches the route property name?
</blockquote></details>

Sounds nice, done.

---

*[demo/vaadin-router-route-actions-demos.html, line 151 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDpxyou-p80PToIeYbW:-LDpzAcp8V_rm0nEdDec:b-uowhsd) ([raw file](https://github.com/vaadin/vaadin-router/blob/a6f10598cdae26d990bbcec9bad54550bbc4a760/demo/vaadin-router-route-actions-demos.html#L151)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

let's capitalise this: "Redirecting from an Action"
</blockquote></details>

Right, always forget about this, thanks.

---

*[demo/vaadin-router-route-actions-demos.html, line 162 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDpyMDp-n0MPqBdBKW8:-LDpzRS95Lk_SAypcNW1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/a6f10598cdae26d990bbcec9bad54550bbc4a760/demo/vaadin-router-route-actions-demos.html#L162)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

let's change "Router redirect" to "Redirects" so that the link text is consistent with the navigation
</blockquote></details>

Done.

---

*[demo/vaadin-router-route-actions-demos.html, line 192 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDpy5Kr07ba61GgM3Dp:-LDpzEJ010P7a961ofYV:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/a6f10598cdae26d990bbcec9bad54550bbc4a760/demo/vaadin-router-route-actions-demos.html#L192)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

let's capitalise this: "Returning Custom Element as an Action Result"
</blockquote></details>

Done.

---

*[demo/vaadin-router-route-actions-demos.html, line 201 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDpyenXCRKYfDJ4Lhcr:-LDpzKUU5cgxpUmKzh6h:bo3vl6y) ([raw file](https://github.com/vaadin/vaadin-router/blob/a6f10598cdae26d990bbcec9bad54550bbc4a760/demo/vaadin-router-route-actions-demos.html#L201)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

"Basic demos" is now called "Getting Started"
</blockquote></details>

Thanks, done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/129)*

**Comment by vlukashov** [comment]
Review status: 5 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/resolver/resolver.js, line 146 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDq-K5x8mm3WJyP71zy:-LDq-K5x8mm3WJyP71zz:b1mc0nl) ([raw file](https://github.com/vaadin/vaadin-router/blob/90dd2a4d3e5cec91201ad60d3f37a98938c41755/src/resolver/resolver.js#L146)):*
> ```JavaScript
>       currentContext = Object.assign({}, context, matches.value);
>       currentContext.redirect = path => redirect(currentContext, path);
>       currentContext.component = component => context.render(component, currentContext);
> ```

(dependencies) Can this be done without introducing a dependency from Resolver to Router?
The resolver layer should not know about the `component` and `redirect` properties.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/129)*

**Comment by vlukashov** [comment]
Review status: 5 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/router.js, line 191 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDq1YnMBkrApQcC5Ehr:-LDq1YnMBkrApQcC5Ehs:bb6lg40) ([raw file](https://github.com/vaadin/vaadin-router/blob/90dd2a4d3e5cec91201ad60d3f37a98938c41755/src/router.js#L191)):*
> ```JavaScript
>         }
>       }
>       return Router.renderComponent(route.component, context);
> ```

For consistency with the `redirect` property this could be `return context.component(route.component)`. And then the `Router.renderComponent()` method can be made private. What do you think?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/129)*

**Comment by SomeoneToIgnore** [comment]
Review status: 5 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/router.js, line 191 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDq1YnMBkrApQcC5Ehr:-LDq2DYX7qIfpWofKdGt:bgrfb36) ([raw file](https://github.com/vaadin/vaadin-router/blob/90dd2a4d3e5cec91201ad60d3f37a98938c41755/src/router.js#L191)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

For consistency with the `redirect` property this could be `return context.component(route.component)`. And then the `Router.renderComponent()` method can be made private. What do you think?
</blockquote></details>

Sounds great, done.

---

*[src/resolver/resolver.js, line 146 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/129#-LDq-K5x8mm3WJyP71zy:-LDq0XeNE6RKHzkMW-mf:b-1eh3wi) ([raw file](https://github.com/vaadin/vaadin-router/blob/90dd2a4d3e5cec91201ad60d3f37a98938c41755/src/resolver/resolver.js#L146)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

(dependencies) Can this be done without introducing a dependency from Resolver to Router?
The resolver layer should not know about the `component` and `redirect` properties.
</blockquote></details>

Sure, done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/129)*

**Comment by vlukashov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/129)*

**Comment by vlukashov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/129)*

**Pull request merged**
