### PR TITLE
feat: add TypeScript declarations

### LINKED ISSUE #304: create TypeScript type declarations for all public APIs
When using Vaadin Router in TypeScript projects I want to have TypeScript type declarations available out of the box so that I can have great DX and take full advantage of TypeScript typing features.

DoD:
 - TypeScript type declaration files `.d.ts` are automatically generated from the source code (i.e. from JSDoc comments)
 - `.d.ts` files are distributed as a part of the `@vaadin/router` npm package

### PR DESCRIPTION
**Pull request by platosha**
Fixes #304

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/353)

### CODE REVIEW

**Comment by abdonrd** [comment]
Great job, @platosha! 👏 

What about the Router constructor and methods (`setRoutes`, `setOutlet`, etc) types?

**Comment by platosha** [comment]
@abdonrd thanks! For now I use the `@polymer/gen-typescript-declarations` tool to generate these type declarations from the existing JSdoc annotations.

To check them out, install latest npm dependencies, run the `$ yarn build` command, then see `dist/vaadin-router.d.ts`.

The `interfaces.d.ts` file only covers the declarations missing from the auto-generated file.

Added a note comment about this to `interfaces.d.ts`.

**Comment by abdonrd** [comment]
@platosha awesome, thanks Anton! 👏

**Comment by abdonrd** [comment]
There are any ETA to release a new version with the types? 🙄

**Comment by vlukashov** [comment]
It was released in [1.4.0](https://github.com/vaadin/vaadin-router/releases/tag/v1.4.0) today.

**Comment by abdonrd** [comment]
Wow! Thanks @vlukashov!

**Comment by trusktr** [comment]
Hello! Are there typings for `vaadin-split-layout`? If so, how do I get those?

**Comment by vlukashov** [comment]
> Hello! Are there typings for `vaadin-split-layout`? If so, how do I get those?

Vaadin components do not have official TS typings at the moment. If you need them in your project, one possibility you have is to use the [`gen-typescript-declarations`](https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations) command from Polymer tools.

**Comment by trusktr** [comment]
Is it generating typings from the JSDoc comments I see here in the router sources?

**Comment by vlukashov** [comment]
The way how the Polymer team [has put it](https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations#faq) is:
> This library is based on Polymer Analyzer which has limitations in its static analysis. For certain patterns, Analyzer relies on additional JSDoc annotations.

In practice I think that the `gen-typescript-declarations` command relies on JSDoc annotations a lot. This is certainly the case when using it to generate `.d.ts` files for Router.

**Pull request merged**
