### PR TITLE
feat(typescript): add `metadata` property to Route

### LINKED ISSUE #444: Feature Request: Route Metadata
Let's say we're implementing a material design nav drawer:

mio-components_assets_1nsuL8VDpBW_LZYXgabK1H0uq6icmmKYt_nav-drawer-intro

In such a case, I might want to keep a record of nav items something like this:

```js
[{
  name: 'My Files',
  path: '/files',
  icon: 'folder',
  isNavRoute: true
}, {
  name: 'Shared with me',
  path: '/shared',
  icon: 'users',
  isNavRoute: true
}]
```

Currently, I would have to keep some of this information in two places at once - here in my record of nav routes, as well as in vaadin-router's route config.

I propose adding a `metadata: Record<string, any>` field to the `Route` interface, which would allow users to add arbitrary metadata (like icon and whether or not to include this route in the nav bar) to their routing table.

## Before:

```js
// app-shell.js
import { router } from './router.js';
const navRoutes = {/* ... some record of nav routes, as above */}
class AppShell extends LitElement {
  routes = somehowCollateRoutes(router.getRoutes(), navRoutes);
  render() {
    return html`
      <mwc-drawer>
        <mwc-list>${this.routes.map(routeTemplate)}</mwc-list>
      </mwc-drawer>
    `;
  }
}
```

## After:
```js
// app-shell.js
import { router } from './router.js';

class AppShell extends LitElement {
  routes = router.getRoutes();
  render() {
    return html`
      <mwc-drawer>
        <mwc-list>${this.routes.map(routeTemplate)}</mwc-list>
      </mwc-drawer>
    `;
  }
}
```

### PR DESCRIPTION
**Pull request by bennypowers**
fixes #444

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/447)

### CODE REVIEW

**Comment by bennypowers** [comment]
@manolo please see new revision

**Comment by abdonrd** [comment]
Any news here?

**Comment by bennypowers** [comment]
see https://github.com/vaadin/vaadin-router/issues/444#issuecomment-613474282

**Comment by abdonrd** [comment]
Nice, thanks @bennypowers!

**Comment by haijian-vaadin** [comment]
Per discussion at https://github.com/vaadin/vaadin-router/issues/444#issuecomment-613474282, let's close this PR and make a new one with the Doc update.

**Pull request closed without merging**
