### PR TITLE
add support for multiple redirects

### LINKED ISSUE #144: Multiple redirects in one resolve pass does not work
Consider the test:

```
it('multiple redirects should work', async() => {
          router.setRoutes([
            {path: '/a', redirect: '/b'},
            {path: '/b', redirect: '/c'},
            {path: '/c', component: 'x-home-view'},
          ]);

          await router.render('/a');

          expect(outlet.children[0].tagName).to.match(/x-home-view/i);
        });
```

Expected: test passes
Actual: an exception is thrown:
```
Error: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
  Router.__setOutletContent at /components/vaadin-router/dist/vaadin-router.umd.js:1533
                  <unknown> at /components/vaadin-router/dist/vaadin-router.umd.js:1487
```

Need to consider if we should support such cases and fix the behavior, if we should.

### PR DESCRIPTION
**Pull request by vlukashov**
Fixes #144

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/194)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @vlukashov)

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-router/194#-LFWUxIB6dlF3qWQPPrJ:-LFWUxIC3KWSswfphv7z:b-awwmwt) (no related file):*
I propose to add a cyclic redirect test and fix it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/194)*

**Comment by vlukashov** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @vlukashov)

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-router/194#-LFWUxIB6dlF3qWQPPrJ:-LFWp0GC9D70Jfk8WxO5:brtn5af) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I propose to add a cyclic redirect test and fix it.
</blockquote></details>

https://github.com/vaadin/vaadin-router/pull/196

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/194)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/194#-:-LFWqPHa-gWlAY69r3F0:bnfp4nl)*

**Comment by vlukashov** [comment]
Review status: 3 of 4 files reviewed, all discussions resolved (waiting on @SomeoneToIgnore and @web-padawan)

---

*[src/router.js, line 379 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/194#-LFWs28h-d8CgeAHMfh_:-LFWsm-e73dX97pLp7eb:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-router/blob/634397ae174adafc34d6fe92423f2da914a508ed/src/router.js#L379)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW can use `log()` to prepend the "Vaadin.Router" to error text. 
Not a blocker, we can revisit error texts later.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/194)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/194)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/194#-:-LFWssxD88OCq-WNngLA:bnfp4nl)*

**Pull request merged**
