### PR TITLE
Support parent layouts

### LINKED ISSUE #26: Parent layouts
As a developer I want to define a common parent layout for a list of child routes so that the common parts of the page layout are defined only once.

As a JavaScript developer, I want to do that purely in JS without using special additional Web Components.

DoD:

* if a route with children defines a component, any content returned when resolving a child route is added as a light DOM child to the parent root's component. The parent's root component with a child is returned back.
* there is a demo of using a parent layout with `<slot>`s and light DOM children

The [common DoD](https://github.com/vaadin/vaadin-router/wiki/Definition-of-Done) applies.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Closes #26

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/169)

### CODE REVIEW

**Comment by vlukashov** [comment]
Review status: 0 of 10 files reviewed, 8 unresolved discussions (waiting on @SomeoneToIgnore)

---

*[demo/vaadin-router-getting-started-demos.html, line 151 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGFXjSDG35tQmvd0Ue:-LFGFXjSDG35tQmvd0Uf:b-8rxgh3) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L151)):*
> ```
> If both route and its child route have a <code>component</code> property, child route's component will be
> ```

This is a short and clear description of _what would happen if..._, but it does not explain why / when this feature may be useful to start with. Could you please re-word the description so that it starts with a use case: master / detail layouts?

Something like
"When blah blah blah it is useful to define a common layout for several pages. With Vaadin.Router this is done by blah blah blah. Check out of the live demo below to see how it works."

---

*[demo/vaadin-router-getting-started-demos.html, line 152 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGGiH7AKF-coE5j4le:-LFGGiH7AKF-coE5j4lf:b-qhacxg) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L152)):*
> ```
> It might not be clear from the previous demos,
> ```

Let's remove this sentence. If our demos fail to make the point clear, we absolutely have to change the demos.

---

*[demo/vaadin-router-getting-started-demos.html, line 156 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGFQMoC5cKZdJsz6HH:-LFGFQMoC5cKZdJsz6HI:b-m8gftz) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L156)):*
> ```HTML
>       This demo shows the nested components.
>     </p>
>     <vaadin-demo-snippet id="vaadin-router-getting-started-demo-4" iframe-src="iframe.html">
> ```

Now this demo looks like it's missing a header. What do you think of adding a separate header to it? Something like 'Nested Components' or 'Parent Layouts'?

---

*[demo/vaadin-router-getting-started-demos.html, line 160 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGHBvP5v2Y9KSVh4IL:-LFGHBvP5v2Y9KSVh4IM:bsxuy2f) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L160)):*
> ```
> class XSlottedUsers
> ```
_slotted_ in the name highlights an implementation detail that makes this component different from others. Can it be changed so that the name focuses on the purpose of the component instead? (e.g. call it `XUsersLayout` or `XUsersMasterView`)

---

*[demo/vaadin-router-getting-started-demos.html, line 179 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGEqHW46ymbpXd5jns:-LFGEqHX-sceugp0QGN_:bnx8pds) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L179)):*
> ```
> <li class='menu'>
> ```

nit: Let's use double quotes to stay consistent with the rest of the demos.

---

*[demo/vaadin-router-getting-started-demos.html, line 198 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGHoffC4pnWrA6xyC0:-LFGHoffC4pnWrA6xyC1:b-5ikw5b) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L198)):*
> ```
> children: [
>     {path: '/:user', component: 'x-user-profile'}
> ]
> ```

What do you think of adding another child view to illustrate the point of the master layout remaining the same when switching between child views?

---

*[src/router.js, line 50 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFDg_UlAyIrKkK1G6FC:-LFDg_Um1vWwaRD2ueUO:b-3c2uy5) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/src/router.js#L50)):*
> ```JavaScript
>     removeFromDomRecursively(node.firstChild);
>   }
>   node.parentNode.removeChild(node);
> ```

Why `node.parentNode.removeChild(node);` was not enough in this case?
It's not obvious to me. Could you please write the reason in a comment?

---

*[src/resolver/resolver.js, line 153 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFDih-f7nYGhnbeWccw:-LFDih-f7nYGhnbeWccx:b-oypogl) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/src/resolver/resolver.js#L153)):*
> ```JavaScript
>       }
> 
>       addRouteToChain(context, matches.value.route);
> ```

Has the behavior changed? Should there be changes in tests as well?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/169)*

**Comment by SomeoneToIgnore** [comment]
Review status: 0 of 10 files reviewed, 8 unresolved discussions (waiting on @SomeoneToIgnore and @vlukashov)

---

*[demo/vaadin-router-getting-started-demos.html, line 151 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGFXjSDG35tQmvd0Ue:-LFGk0ysAYRJJsE40hkP:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L151)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> If both route and its child route have a <code>component</code> property, child route's component will be
> ```

This is a short and clear description of _what would happen if..._, but it does not explain why / when this feature may be useful to start with. Could you please re-word the description so that it starts with a use case: master / detail layouts?

Something like
"When blah blah blah it is useful to define a common layout for several pages. With Vaadin.Router this is done by blah blah blah. Check out of the live demo below to see how it works."
</blockquote></details>

Done.

---

*[demo/vaadin-router-getting-started-demos.html, line 152 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGGiH7AKF-coE5j4le:-LFGgl6K2m78lvuZxX_E:b773fxe) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L152)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> It might not be clear from the previous demos,
> ```

Let's remove this sentence. If our demos fail to make the point clear, we absolutely have to change the demos.
</blockquote></details>

Right, done :)

---

*[demo/vaadin-router-getting-started-demos.html, line 156 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGFQMoC5cKZdJsz6HH:-LFGgbOX-UlCkvV2dXU3:b-bm5ip9) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L156)):*
> Nested Components

Have picked this, thanks.

---

*[demo/vaadin-router-getting-started-demos.html, line 160 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGHBvP5v2Y9KSVh4IL:-LFGgTMe7FrOKjBPPAtD:b-pek69l) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L160)):*
> XUsersLayout

Have used this, thanks.

---

*[demo/vaadin-router-getting-started-demos.html, line 179 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGEqHW46ymbpXd5jns:-LFGe5hL2JvP4Tn69DgZ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L179)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> <li class='menu'>
> ```

nit: Let's use double quotes to stay consistent with the rest of the demos.
</blockquote></details>

Done.

---

*[demo/vaadin-router-getting-started-demos.html, line 198 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGHoffC4pnWrA6xyC0:-LFGfcHc69YXtQbLio-f:b-ts42p4) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L198)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> children: [
>     {path: '/:user', component: 'x-user-profile'}
> ]
> ```

What do you think of adding another child view to illustrate the point of the master layout remaining the same when switching between child views?
</blockquote></details>

Why not, added.

---

*[src/router.js, line 50 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFDg_UlAyIrKkK1G6FC:-LFGbzn13F_l19JBsKOv:bgw7rhn) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/src/router.js#L50)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Why `node.parentNode.removeChild(node);` was not enough in this case?
It's not obvious to me. Could you please write the reason in a comment?
</blockquote></details>

Sure, done, had written it in the place where method is used.

The reason for this is that I think we should call `onBeforeLeave` and `disconnectedCallback` in the same order.
Refer to the '/a/b -> /c' test: 
```
await router.render('/c');

expect(callbacksLog).to.deep.equal([
'x-c.action',
'x-b.onBeforeLeave',
'x-a.onBeforeLeave',
'x-c.onBeforeEnter',
'x-b.disconnectedCallback', //this is called first only because we remove the elements recursively from the bottom
'x-a.disconnectedCallback',
'x-c.connectedCallback',
'x-c.onAfterEnter',
]);
```

---

*[src/resolver/resolver.js, line 153 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFDih-f7nYGhnbeWccw:-LFGa5ek-xG4pGpRgxMY:betd107) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/src/resolver/resolver.js#L153)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Has the behavior changed? Should there be changes in tests as well?
</blockquote></details>

The trick is that it did not changed the old functionality: after you call `Resolver.resolve`, you still get the context with `chain` populated.

What had changed is that `next()` method call now updates previous context's `chain` by appending the next route resolved.
I additionally test this in resolver tests, if needed, now it's implicitly tested by all new tests since whole implementation depends on it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/169)*

**Comment by SomeoneToIgnore** [comment]
*[demo/vaadin-router-getting-started-demos.html, line 165 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGfPKp9b3v1xbDNC4c:-LFGm6l3CBMvGeWUc7ob:b-o419a3) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L165)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

let's rearrange the demo, so that Router config is on the top (user should see it without any scrolling)

also, Polymer 2 syntax is verbose and I recommend using `dom-module` and Polymer 1 compatible syntax (so it would be easier to adapt demos for vaadin.com)
</blockquote></details>

Right, fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/169)*

**Comment by vlukashov** [comment]
Review status: 1 of 10 files reviewed, 5 unresolved discussions (waiting on @vlukashov and @web-padawan)

---

*[demo/vaadin-router-getting-started-demos.html, line 160 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGHBvP5v2Y9KSVh4IL:-LFH1vZmDzALkWsnIRGz:b3b49c1) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L160)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> XUsersLayout

Have used this, thanks.
</blockquote></details>

How about the tag name? It's still `x-slotted-users`.

---

*[demo/vaadin-router-getting-started-demos.html, line 198 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGHoffC4pnWrA6xyC0:-LFH334j0OheIv5Yd_Aa:b-2g9x2u) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L198)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Why not, added.
</blockquote></details>

The example with 
```
children: [
  {path: '/([0-9]+)', component: 'x-not-found-view'},
  {path: '/:user', component: 'x-user-profile'},
]
```
looks a bit artificial.


How about something looking more like a real-life app (think of bakery or beverage buddy)?
Here is one example:
```
path: '/',
component: 'x-main-layout',
children: [
  {path: '/', component: 'x-home-view'},
  {path: '/user', component: 'x-user-list'},
  {path: '/user/:user', component: 'x-user-profile'},
]
```

---

*[src/router.js, line 50 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFDg_UlAyIrKkK1G6FC:-LFH4UqD6lQxAK_3UrQv:b-k5f92w) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/src/router.js#L50)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Sure, done, had written it in the place where method is used.

The reason for this is that I think we should call `onBeforeLeave` and `disconnectedCallback` in the same order.
Refer to the '/a/b -> /c' test: 
```
await router.render('/c');

expect(callbacksLog).to.deep.equal([
'x-c.action',
'x-b.onBeforeLeave',
'x-a.onBeforeLeave',
'x-c.onBeforeEnter',
'x-b.disconnectedCallback', //this is called first only because we remove the elements recursively from the bottom
'x-a.disconnectedCallback',
'x-c.connectedCallback',
'x-c.onAfterEnter',
]);
```
</blockquote></details>

I would say, it's OK to let the browser to decide the order in which it calls `disconnectedCallback`s and if the users want to have a definitive order, they should use the `onAfterLeave` callbacks instead. So, if that does not prevent any of our internal use cases, then for the sake of simplicity and #UseThePlatform, I'd suggest to keep it as `node.parentNode.removeChild(node);`.

Also, I am not sure but I have a gut feeling that such manual recursive DOM removal might be considerably slower on large DOM trees (this of course needs checking).

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/169)*

**Comment by SomeoneToIgnore** [comment]
Review status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @vlukashov, @SomeoneToIgnore, and @web-padawan)

---

*[demo/vaadin-router-getting-started-demos.html, line 160 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGHBvP5v2Y9KSVh4IL:-LFHJct-6KyiUrIlNCtl:b-p4ybu) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L160)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

How about the tag name? It's still `x-slotted-users`.
</blockquote></details>

Oops, fixed.

---

*[demo/vaadin-router-getting-started-demos.html, line 198 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFGHoffC4pnWrA6xyC0:-LFHMkyYBXrrgjoT5mOD:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/demo/vaadin-router-getting-started-demos.html#L198)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

The example with 
```
children: [
  {path: '/([0-9]+)', component: 'x-not-found-view'},
  {path: '/:user', component: 'x-user-profile'},
]
```
looks a bit artificial.


How about something looking more like a real-life app (think of bakery or beverage buddy)?
Here is one example:
```
path: '/',
component: 'x-main-layout',
children: [
  {path: '/', component: 'x-home-view'},
  {path: '/user', component: 'x-user-list'},
  {path: '/user/:user', component: 'x-user-profile'},
]
```
</blockquote></details>

Done.

---

*[src/router.js, line 50 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/169#-LFDg_UlAyIrKkK1G6FC:-LFHJqbq6pKmbJih5Wlj:b2lc8ad) ([raw file](https://github.com/vaadin/vaadin-router/blob/d1a9ee1742397dc41ab0e80d39299b5e8db51267/src/router.js#L50)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

I would say, it's OK to let the browser to decide the order in which it calls `disconnectedCallback`s and if the users want to have a definitive order, they should use the `onAfterLeave` callbacks instead. So, if that does not prevent any of our internal use cases, then for the sake of simplicity and #UseThePlatform, I'd suggest to keep it as `node.parentNode.removeChild(node);`.

Also, I am not sure but I have a gut feeling that such manual recursive DOM removal might be considerably slower on large DOM trees (this of course needs checking).
</blockquote></details>

Ok, adjusted the code.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/169)*

**Comment by vlukashov** [comment]
:lgtm:

---

Reviewed 6 of 8 files at r1, 1 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @web-padawan)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/169#-:-LFHRvGc7wjmKLKDIn6S:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 6 of 8 files at r1, 3 of 3 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/169)*

**Pull request merged**
