### PR TITLE
Add routing JS API

### LINKED ISSUE #27: Routing config JS API
As a developer I want to have a JS API to add / remove routes at the run time, so that I can add routes from a bundle or a route component.

Adding sub-routes dynamically allows non-monolithic app structures so that the teams working on different parts of the app are free to define the routing structures for their sub routes without a central coordination.

DoD:

* the router JS API has methods to get / add / remove routes
* it should be possible to add routes from inside a route action so that the added routes are visited in the same resolve pass (i.g. add a `/users/:user` route inside the `/user` route action so that calling `context.next()` after `router.addRoutes()` would go to the new route).
* no demos since this is mostly an internal feature - the user value comes from the stories this feature enables

The [common DoD](https://github.com/vaadin/vaadin-router/wiki/Definition-of-Done) applies.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Closes #27

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/185)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
*[test/router/router.spec.html, line 636 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFNUIP1Bx9PLKK-H9pR:-LFNUIP240EWG0wjOIyg:bvqfsmx) ([raw file](https://github.com/vaadin/vaadin-router/blob/2e8c078ce016d36662e8f500272c8bd35f705da2/test/router/router.spec.html#L636)):*
> ```HTML
>           it('action that added a route is able to resolve it', async() => {
>             router.setRoutes([
>               {path: '/users/(.*?)', action: context => {
> ```

This seems to be the only way it works now: in order to be able to add a new route dynamically, previous route should be resolvable in the beginning.
I've spent quite some time trying to make it work differently (for instance, without `/(.*?)` part in the original route), but failed to make anything proper.
If this is not what's expected in the ticket, let's  discuss it later.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/185)*

**Comment by SomeoneToIgnore** [comment]
Ready to be reviewed again.

---

Review status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @SomeoneToIgnore)

---

*[src/router.js, line 116 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFQbjRg366g0h0h_IOM:-LFU1u2h3Gdl5lzgjtpy:b-1j0zqj) ([raw file](https://github.com/vaadin/vaadin-router/blob/b6102faf465e4edce82b4ad5c507ba8424bab3b9/src/router.js#L116)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> addRoutes: routes => this.addRoutes(routes),
> ```
Is there now a difference between `context.addRoutes()` and `context.resolver.addRoutes()`?

If we expose a specialized method on the `context`, I suggest to call it `addChildren()` and to make it append the new routes as _children_ of the route currently being resolved. Let's discuss.
</blockquote></details>

Reworked as agreed, no more extra methods for action.

---

*[test/router/router.spec.html, line 636 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFNUIP1Bx9PLKK-H9pR:-LFU1y3V4VnzX5O668H9:bhfz0qn) ([raw file](https://github.com/vaadin/vaadin-router/blob/2e8c078ce016d36662e8f500272c8bd35f705da2/test/router/router.spec.html#L636)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

In one way or another the router needs to know that this route should match any pathname starting with `/users/` even though it does not have children listed in the routes config explicitly.

I can see at least three alternatives:
 - use the regexp pattern like you've done (nit: `/users/(.*)` might be enough)
 - add a `children: true` property to the route object
 - add a new property to the route object that would instruct the router to match this route event if it is only a prefix match

I am leaning towards the 2nd or the 1st option.
</blockquote></details>

Reworked as agreed: `children` now can be a function.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/185#-:-LFU1qhG-clKjMdF-Fm7:bohunlp)*

**Comment by vlukashov** [comment]
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @SomeoneToIgnore)

---

*[src/router.js, line 165 at r4](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFWAto76coXTDCUlcDv:-LFWAto8DGRNnMVE0qQo:b-7r673f) ([raw file](https://github.com/vaadin/vaadin-router/blob/c028ab1f12f427c4303ce0433adf15e81bec007a/src/router.js#L165)):*
> ```JavaScript
>     }
> 
>     return callbacks.then(() => runCallbackIfPossible(route.children, Object.assign({}, context, {next: undefined}), route))
> ```

The `children` callback is called only once and not necessarily with the context that ever gets rendered (thinking of redirects, prevented transitions and abandoned renders here). In that situation I suggest to not pass the context object at all (because it is rather unreliable).

---

*[src/router.js, line 168 at r4](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFW0OMQ5tTEl3GguIJj:-LFW0OMR6dtj8tSHJA13:b-6qw04u) ([raw file](https://github.com/vaadin/vaadin-router/blob/c028ab1f12f427c4303ce0433adf15e81bec007a/src/router.js#L168)):*
> ```JavaScript
>       .then(newChildren => {
>         if (typeof route.children === 'function') {
>           delete route.children;
> ```

In my mind it may be confusing that a property set on a route object by a developer gets implicitly changed.

Let's not delete the original property value but rather save the calculated children into a new `route.__children` property and use that everywhere in router and resovler. If `children` is an array, set `__children` to point to the same array. What do you think?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/185)*

**Comment by SomeoneToIgnore** [comment]
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @SomeoneToIgnore)

---

*[src/router.js, line 165 at r4](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFWAto76coXTDCUlcDv:-LFWGz6e-jeYbe0phFIQ:b-d2qlec) ([raw file](https://github.com/vaadin/vaadin-router/blob/c028ab1f12f427c4303ce0433adf15e81bec007a/src/router.js#L165)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

The `children` callback is called only once and not necessarily with the context that ever gets rendered (thinking of redirects, prevented transitions and abandoned renders here). In that situation I suggest to not pass the context object at all (because it is rather unreliable).
</blockquote></details>

Makes sense, I've also had doubts about it, removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/185)*

**Comment by vlukashov** [comment]
Review status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @SomeoneToIgnore and @vlukashov)

---

*[src/router.js, line 165 at r4](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFWAto76coXTDCUlcDv:-LFWWtXd4z2N7MrkAW3J:b-m7k55j) ([raw file](https://github.com/vaadin/vaadin-router/blob/c028ab1f12f427c4303ce0433adf15e81bec007a/src/router.js#L165)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Makes sense, I've also had doubts about it, removed.
</blockquote></details>

nit: no parameter is `undefined`, not `null`
(`typeof null === 'object'`)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/185)*

**Comment by SomeoneToIgnore** [comment]
*[src/router.js, line 165 at r4](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFWAto76coXTDCUlcDv:-LFWXSltE735bEdHg4io:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/c028ab1f12f427c4303ce0433adf15e81bec007a/src/router.js#L165)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

nit: no parameter is `undefined`, not `null`
(`typeof null === 'object'`)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/185)*

**Comment by web-padawan** [comment]
Reviewed 1 of 4 files at r1, 1 of 4 files at r4, 1 of 3 files at r5, 5 of 5 files at r6.
Review status: all files reviewed, 6 unresolved discussions (waiting on @vlukashov and @SomeoneToIgnore)

---

*[src/router.js, line 57 at r6](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFqRbVx9VWxYRphEZGy:-LFqRbVy4R5aUUhlDoIU:bqcco9a) ([raw file](https://github.com/vaadin/vaadin-router/blob/57fd2df838648bc89fdd49743da3e1c17841a49c/src/router.js#L57)):*
> ```JavaScript
> function processNewChildren(newChildren, route, context) {
>   if (typeof newChildren !== 'object') {
>     throw new Error(log(`Expected 'children' method  of the route with path '${route.path}' `
> ```

nit: extra whitespace after "method"
also, we could just use newlines, since we already use ES6 template literal (which allows those), instead of concatenating strings

---

*[src/router.js, line 62 at r6](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFqS3T30OXjZDqO-tNY:-LFqS3T30OXjZDqO-tNZ:b9dy9oh) ([raw file](https://github.com/vaadin/vaadin-router/blob/57fd2df838648bc89fdd49743da3e1c17841a49c/src/router.js#L62)):*
> ```JavaScript
> 
>   route.__children = [];
>   const childRoutes = toArray(newChildren);
> ```

BTW can we just require user to return an array instead of object, and use Array.isArray() check in the line above? What is the case for accepting both array and object values here?

---

*[src/utils.js, line 18 at r6](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFqV2Xa-Z1Um3vZ26Ax:-LFqV2Xa-Z1Um3vZ26Ay:bch8yvd) ([raw file](https://github.com/vaadin/vaadin-router/blob/57fd2df838648bc89fdd49743da3e1c17841a49c/src/utils.js#L18)):*
> ```JavaScript
> 
>   const stringKeys = ['component', 'redirect', 'bundle'];
>   if (typeof route.action !== 'function' && !Array.isArray(route.children) && typeof route.children !== 'function'
> ```

it seems like we have enough typeof checks in this file for `isFunc()` and `isString()` helpers, e. g.

```js
const isFunc = f => typeof f == 'function';
const isString = s => typeof f == 'string';
```

---

*[src/resolver/matchRoute.js, line 75 at r6](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFqVw_v49mnMHGSOM-3:-LFqVw_v49mnMHGSOM-4:b3evld) ([raw file](https://github.com/vaadin/vaadin-router/blob/57fd2df838648bc89fdd49743da3e1c17841a49c/src/resolver/matchRoute.js#L75)):*
> ```JavaScript
>       }
> 
>       const children = route.__children = route.__children || route.children;
> ```

what if the empty array is here? any length checks, or maybe a test for this case?

---

*[src/resolver/resolver.js, line 74 at r6](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFqTSHK3b2pnhHmoltt:-LFqTSHK3b2pnhHmoltu:boorgae) ([raw file](https://github.com/vaadin/vaadin-router/blob/57fd2df838648bc89fdd49743da3e1c17841a49c/src/resolver/resolver.js#L74)):*
> ```JavaScript
>    */
>   getRoutes() {
>     return [...this.root.__children];
> ```

while we are here, and now using private property: why don't we use `.slice(0)` for shallow copy?

ideally, it would be nice to avoid array rest operator (we have it in 3 places), to get rid of the Bsbel helper:

```js
  var toConsumableArray = function (arr) {
    if (Array.isArray(arr)) {
      for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) arr2[i] = arr[i];

      return arr2;
    } else {
      return Array.from(arr);
    }
  };

```

it does not make much sense for us to have it, as this is the output where is it used:
```js
{
      key: 'getRoutes',
      value: function getRoutes() {
        return [].concat(toConsumableArray(this.root.children));
      }

    }, {
      key: 'setRoutes',
      value: function setRoutes(routes) {
        ensureRoutes(routes);
        this.root.children = [].concat(toConsumableArray(toArray(routes)));
      }

    }, {
      key: 'addRoutes',
      value: function addRoutes(routes) {
        var _root$children;

        ensureRoutes(routes);
        (_root$children = this.root.children).push.apply(_root$children, toConsumableArray(toArray(routes)));
      }
```
as you can see, in all the 3 cases the helper is redundant: we are already sure we have the array after using our own `toArray` helper, as well as for `__children` property,

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/185)*

**Comment by vlukashov** [comment]
Review status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @web-padawan, @vlukashov, and @SomeoneToIgnore)

---

*[src/router.js, line 57 at r6](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFqRbVx9VWxYRphEZGy:-LFq_GOO7Er8nqSH-Ffv:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-router/blob/57fd2df838648bc89fdd49743da3e1c17841a49c/src/router.js#L57)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: extra whitespace after "method"
also, we could just use newlines, since we already use ES6 template literal (which allows those), instead of concatenating strings
</blockquote></details>

done

---

*[src/router.js, line 62 at r6](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFqS3T30OXjZDqO-tNY:-LFq_3zl6B0tAlSgwVIs:b-icg3rk) ([raw file](https://github.com/vaadin/vaadin-router/blob/57fd2df838648bc89fdd49743da3e1c17841a49c/src/router.js#L62)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW can we just require user to return an array instead of object, and use Array.isArray() check in the line above? What is the case for accepting both array and object values here?
</blockquote></details>

The only use case for supporting both an array an a single route is when there is only one child route. Then it's a nice feature that developers can omit the array brackets.

---

*[src/utils.js, line 18 at r6](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFqV2Xa-Z1Um3vZ26Ax:-LFqdbFSB0ozjj1kb78e:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-router/blob/57fd2df838648bc89fdd49743da3e1c17841a49c/src/utils.js#L18)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

it seems like we have enough typeof checks in this file for `isFunc()` and `isString()` helpers, e. g.

```js
const isFunc = f => typeof f == 'function';
const isString = s => typeof f == 'string';
```
</blockquote></details>

done

---

*[src/resolver/matchRoute.js, line 75 at r6](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFqVw_v49mnMHGSOM-3:-LFqdcvl3QlcE7f3-iiE:b-11zhn) ([raw file](https://github.com/vaadin/vaadin-router/blob/57fd2df838648bc89fdd49743da3e1c17841a49c/src/resolver/matchRoute.js#L75)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

what if the empty array is here? any length checks, or maybe a test for this case?
</blockquote></details>

In my mind, an empty array of children is an edge case, but it's supported. I've added a test case for the Resolver class.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/185)*

**Comment by web-padawan** [comment]
Reviewed 8 of 8 files at r7.
Review status: all files reviewed, 2 unresolved discussions (waiting on @vlukashov and @SomeoneToIgnore)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/185)*

**Comment by SomeoneToIgnore** [comment]
Review status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @web-padawan, @vlukashov, and @SomeoneToIgnore)

---

*[test/router/router.spec.html, line 1081 at r9](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFv-f_ZEKIyHpx0-J9_:-LFv-f_ZEKIyHpx0-J9a:b-mr3i83) ([raw file](https://github.com/vaadin/vaadin-router/blob/f859932140dfd54038522ff31fc3ba7dff3a8e0a/test/router/router.spec.html#L1081)):*
> ```HTML
>               expect(context.cancel).to.be.an('undefined');
>               expect(context.redirect).to.be.an('undefined');
>               expect(context.component).to.be.an('undefined');
> ```

Should we also check this: `expect(context.next).to.be.an('undefined');`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/185)*

**Comment by vlukashov** [comment]
Review status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @web-padawan and @SomeoneToIgnore)

---

*[src/resolver/resolver.js, line 74 at r6](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFqTSHK3b2pnhHmoltt:-LFv-UlE0WThnJevq25q:b-yojdfa) ([raw file](https://github.com/vaadin/vaadin-router/blob/57fd2df838648bc89fdd49743da3e1c17841a49c/src/resolver/resolver.js#L74)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

while we are here, and now using private property: why don't we use `.slice(0)` for shallow copy?

ideally, it would be nice to avoid array rest operator (we have it in 3 places), to get rid of the Bsbel helper:

```js
  var toConsumableArray = function (arr) {
    if (Array.isArray(arr)) {
      for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) arr2[i] = arr[i];

      return arr2;
    } else {
      return Array.from(arr);
    }
  };

```

it does not make much sense for us to have it, as this is the output where is it used:
```js
{
      key: 'getRoutes',
      value: function getRoutes() {
        return [].concat(toConsumableArray(this.root.children));
      }

    }, {
      key: 'setRoutes',
      value: function setRoutes(routes) {
        ensureRoutes(routes);
        this.root.children = [].concat(toConsumableArray(toArray(routes)));
      }

    }, {
      key: 'addRoutes',
      value: function addRoutes(routes) {
        var _root$children;

        ensureRoutes(routes);
        (_root$children = this.root.children).push.apply(_root$children, toConsumableArray(toArray(routes)));
      }
```
as you can see, in all the 3 cases the helper is redundant: we are already sure we have the array after using our own `toArray` helper, as well as for `__children` property,
</blockquote></details>

Replacing the spread operator with `.slice()` makes the minzipped UMD bundle 43 bytes smaller, and the module bundle 10 bytes larger. I think it's OK to keep the spread operator.

---

*[test/router/router.spec.html, line 1081 at r9](https://reviewable.io/reviews/vaadin/vaadin-router/185#-LFv-f_ZEKIyHpx0-J9_:-LFv1-rc4MrfaywY1sNE:b-kl8g4c) ([raw file](https://github.com/vaadin/vaadin-router/blob/f859932140dfd54038522ff31fc3ba7dff3a8e0a/test/router/router.spec.html#L1081)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Should we also check this: `expect(context.next).to.be.an('undefined');`?
</blockquote></details>

good catch!

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/185)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r10.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/185)*

**Pull request merged**
