### PR TITLE
Add the demo for ambiguous match

### LINKED ISSUE #31: Ambiguous matches
As a developer I want to define ambiguous URL matching rules (i.e. several routes would match at the same time) so that I could have shorter URLs in my app. E.g. /company, /about and /:user instead of /company, /about and /users/:user. When the rules are ambiguous the order in which the rules are defined should determine the matching route.

DoD:

* The following sample should work as expected (`/` matches the home view, `/about` matches the about view, `/anything/else` matches the user view)

```javascript
router.setRoutes([
  { path: '/', exact: true, component: 'src/x-home-view.html' },
  { path: '/about', component: 'src/x-about-view.html' },
  { path: '/:user', component: 'src/x-user-view.html' },
]);
```
* There is a demo showing that the order in which the routes are defined matters

The [common DoD](https://github.com/vaadin/vaadin-router/wiki/Definition-of-Done) applies.

### PR DESCRIPTION
**Pull request by web-padawan**
Closes #31

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/102)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/102)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/102#-:-LD5qizWDVt3xwQExpLV:bnfp4nl)*

**Comment by vlukashov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/102#-:-LD6O0Y12sJNWIqHyjaS:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 3 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/102)*

**Pull request merged**
