### PR TITLE
Extract common test method to test-utils.js

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/163)

### CODE REVIEW

**Comment by vlukashov** [comment]
Review status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SomeoneToIgnore)

---

*[test/router/lifecycle-events.spec.html, line 132 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/163#-LEsxScu5TVjOBO7105y:-LEsxScu5TVjOBO7105z:b-o4t42t) ([raw file](https://github.com/vaadin/vaadin-router/blob/3741ef587b2832dfb7a49f2ab3712d5d0a96c964/test/router/lifecycle-events.spec.html#L132)):*
> ```HTML
> 
>           expect(outlet.children[0].tagName).to.match(/x-users-list/i);
>           window.VaadinTestNamespace.verifyActiveRoutes(router, ['/users']);
> ```

Now the `window.VaadinTestNamespace.` bit is repeated a number of times. How about having `const {verifyActiveRoutes} = VaadinTestNamespace;` only once somewhere in the top of the page?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/163)*

**Comment by vlukashov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @SomeoneToIgnore)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/163)*

**Comment by vlukashov** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/163)*

**Comment by SomeoneToIgnore** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[test/router/lifecycle-events.spec.html, line 132 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/163#-LEsxScu5TVjOBO7105y:-LEsyC8M9ns63oLcBvsI:bcus9ab) ([raw file](https://github.com/vaadin/vaadin-router/blob/3741ef587b2832dfb7a49f2ab3712d5d0a96c964/test/router/lifecycle-events.spec.html#L132)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Now the `window.VaadinTestNamespace.` bit is repeated a number of times. How about having `const {verifyActiveRoutes} = VaadinTestNamespace;` only once somewhere in the top of the page?
</blockquote></details>

Nice idea, done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/163)*

**Pull request merged**
