### PR TITLE
Fixes from the 2nd DX tests session

### PR DESCRIPTION
**Pull request by vlukashov**
- clarify the Getting Started demo
 -- remove the link to the advanced 'Navigation Triggers' topic from the first paragraph of the Getting Started instructinos (to avoid leading people away into complicated stuff)
 -- update the installation instructions (make sure all examples work, make it clear for Webpack users)
 -- remove references to bower_components (replace with unpkg.com)
 -- move the live demo higher up (above the route property descriprion)
- rename basic demos into getting-started (all files)
- rename the Prevent Navigation demo into Lifecycle Events
- add lifecycle events description
- add a note that lifecycle callbacks may be async

Based on the feedback from #153

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/162)

### CODE REVIEW

**Comment by vlukashov** [comment]
Review status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @web-padawan and @vlukashov)

---

*[demo/vaadin-router-lifecycle-events-demos.html, line 42 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/162#-LEtG9zx7mCRlZan2-Zq:-LEu8uoM8NkEwTSjMeXZ:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-router/blob/2e26f20d3b2347ed15c5dc3b8d0dd9044ed55a58/demo/vaadin-router-lifecycle-events-demos.html#L42)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: the dot in the end of this line is not necessary
</blockquote></details>

done

---

*[demo/vaadin-router-lifecycle-events-demos.html, line 52 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/162#-LEtGhlW8RM9irztJqFT:-LEu8vmK5HX3l7zP-vkC:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-router/blob/2e26f20d3b2347ed15c5dc3b8d0dd9044ed55a58/demo/vaadin-router-lifecycle-events-demos.html#L52)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: missing the dot in the end of the sentence
</blockquote></details>

done

---

*[demo/vaadin-router-lifecycle-events-demos.html, line 63 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/162#-LEtGw_R1htKkXSr6f60:-LEu8wig5if3GJbDZrVe:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-router/blob/2e26f20d3b2347ed15c5dc3b8d0dd9044ed55a58/demo/vaadin-router-lifecycle-events-demos.html#L63)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Consider rewording this to make it clear that only router specific callbacks can return Promise, not native ones
</blockquote></details>

done

---

*[demo/vaadin-router-lifecycle-events-demos.html, line 65 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/162#-LEtHAI35Ah6VqKEWxZb:-LEu8xTa6dfmFSxqlHQ7:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-router/blob/2e26f20d3b2347ed15c5dc3b8d0dd9044ed55a58/demo/vaadin-router-lifecycle-events-demos.html#L65)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

1. Try using the link like this (should work both locally and on GH pages)

```
<a href="../#/classes/Vaadin.WebComponentInterface" target="_blank">WebComponentInterface</a>
```

2. nit: extra whitespace before "See"
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/162)*

**Comment by vlukashov** [comment]
Review status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @web-padawan)

---

*[demo/vaadin-router-lifecycle-events-demos.html, line 25 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/162#-LEtGoAi0MJbIwY08bV0:-LEu92822dSZx9g3f_01:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-router/blob/2e26f20d3b2347ed15c5dc3b8d0dd9044ed55a58/demo/vaadin-router-lifecycle-events-demos.html#L25)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: missing the dot in the end of the sentence

BTW consider using use "native Custom Element callback", with a link to the spec: 
https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-reactions
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/162)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/162)*

**Comment by SomeoneToIgnore** [comment]
*[demo/vaadin-router-lifecycle-events-demos.html, line 27 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/162#-LEuzIG3DLciTIrxxTyT:-LEuzIG42nDSp3GErfTR:b2gyb6p) ([raw file](https://github.com/vaadin/vaadin-router/blob/1e6924c62995426a340d86c1b2d81c3dc40d07da/demo/vaadin-router-lifecycle-events-demos.html#L27)):*
> ```
> native
> ```


Should it be `inactive`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/162)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @vlukashov)

---

*[demo/vaadin-router-lifecycle-events-demos.html, line 27 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/162#-LEuzIG3DLciTIrxxTyT:-LEuzrUf8yPQznSUjurX:bnd0ckj) ([raw file](https://github.com/vaadin/vaadin-router/blob/1e6924c62995426a340d86c1b2d81c3dc40d07da/demo/vaadin-router-lifecycle-events-demos.html#L27)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> native
> ```


Should it be `inactive`?
</blockquote></details>

Same below, for the other callback.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/162)*

**Comment by web-padawan** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @vlukashov)

---

*[demo/vaadin-router-lifecycle-events-demos.html, line 27 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/162#-LEuzIG3DLciTIrxxTyT:-LEwfTF517GYrxsFhDfj:b-k46i) ([raw file](https://github.com/vaadin/vaadin-router/blob/1e6924c62995426a340d86c1b2d81c3dc40d07da/demo/vaadin-router-lifecycle-events-demos.html#L27)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Same below, for the other callback.
</blockquote></details>

Native means "callback defined by Custom Elements spec", in contrary to callbacks added by Router

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/162)*

**Comment by web-padawan** [comment]
Dismissed @SomeoneToIgnore from a discussion.
Review status: all files reviewed, 1 unresolved discussion (waiting on @vlukashov)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/162)*

**Comment by web-padawan** [comment]
OK regenerate docs then LGTM

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/162#-:-LEwg0_e1TdJU3nr1T_i:b-sskm8l)*

**Comment by vlukashov** [comment]
done

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2, 7 of 7 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/162#-:-LEwlRAN4CmKPRAShENG:bb7f2mf)*

**Pull request merged**
