### PR TITLE
feat: add searchParams for RouterLocation

### PR DESCRIPTION
**Pull request by haijian-vaadin**
For https://github.com/vaadin/vaadin-router/issues/498

### CODE REVIEW

**Review by platosha — APPROVED** [review]

**Comment by abdonrd** [comment]
@haijian-vaadin @platosha when a new release with this? Thanks!

**Comment by nChauhan91** [comment]
This feature `searchParams` shows it was merged into master a year ago & also is present in documentation but hasn't been released yet & in not present in current version `1.7.4` , is this correct or am i missing something?

`getPageNumber(location) {
      return location.searchParams.get('page') || 'none';
    }
`

**Comment by chumaltd** [comment]
@platosha +1 long awaited 1.7.5 release with this feature!!!

**Comment by danielquintero** [comment]
why is this closed? it is not included in 1.7.5 release... I tried npm i and downloading the sources, yet no reference to searchParams appears. Can someone do a fix release to include this?

**Comment by danielquintero** [comment]
@haijian-vaadin I am trying to use this feature however I am on 1.7.5 and I do not see any searchParams within location object, could you clarify if this landed in 1.7.5 or not?

**Pull request merged**
