### PR TITLE
Track active state of routes

### LINKED ISSUE #22: Route 'active' state tracking
As a developer I want to detect events when a route becomes 'active' (i.e. it gets visited in a resolve pass, while it was skipped by the previous resolve pass), and 'inactive' (i.e. an 'active' route does not get visited in a resolve pass).

While this feature might not have a direct user value, it is a prerequisite for a number of other stories.

DoD:

* there is an `activeRoutes` read-only array property on the router object. It is an array containing the full chain of routes that were traversed in the last render's resolve pass--from the root to a leaf. Initially it is an empty array.
* the `activeRoutes` array is updated to the new routes chain every time when a render pass is completed, after the router outlet content is updated.
* a route object may have an `inactivate` property (`function (context) => Promise<RenderResult>`). During each render's resolve pass a new `activeRoutes` chain is constructed (starting from the root route). As each new route is added to the new `activeRoutes` chain, the new chain is compared to the last `activeRoutes` chain. As long as the active routes in the new chain remain the same as they were in the last chain, no additional actions are taken. When the new active chain is about to diverge from the last active chain (i.e. when the new resolve pass is about to resolve a route which was not a part of the last resove chain), the tail of the last active route chain is 'inactivated' before the new route resolution starts.

  Example:
  Routes config:
```
  [
      {path: '/', component: 'x-home-view'},
      {path: '/users', component: 'x-users-list-view'},
      {path: '/users/new', component: 'x-new-user-view'},
      {path: '/users/:user', component: 'x-user-profile-view'},
  ]
```

  Last active route chain: `['/', '/users', '/users/:user']`

  The new pathname to render: `'/users/new'`

  The new active route chain before calling `resolveRoute()` for the `'/users/new'` route: `['/', '/users']`. It matches the beginning of the last active route chain.

  The `'/users/new'` route, when appended to the new active routes chain, would make it diverge from the last active route chain: the 3rd item in the array is going to be different.
  At that point, before calling `'resolveRoute'` for the `'/users/new'` route, the tail of the last active route chain after the divergence point is 'inactivated'. It's only one route in this example: `'/users/:user'`. In a generic case, all views in that chain should be inactivated in sequence starting from the end of the chain.

* 'Inactivating' a route without the `inactivate` property is a no-op.
* 'Inactivating' a route with the `inactivate` property means that the function defined by that property is called with the current render context. If the `inactivate` function returns a non-null, non-undefined result, the render pass ends with that result and the active route chain does not change (i.e. inactivation is prevented).
* If a render's resolve pass ends, and the new active routes chain is shorter than the last active routes chain, the tail of the last active routes chain is 'inactivated' before the render is completed. E.g. when navigating from `'/users/sam'` to `'/users'` the `'/users/:user'` route should be successfully inactivated before the new view chain can become active.
* (no demos--this is an internal feature--but thorough testing)

The [common DoD](https://github.com/vaadin/vaadin-router/wiki/Definition-of-Done) applies.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Closes #22

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)

### CODE REVIEW

**Comment by vlukashov** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---

*[test/router/dynamic.redirect.spec.html, line 98 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDfuKZV1WiVALhBAUJ_:-LDfuKZV1WiVALhBAUJa:bbeuhlk) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L98)):*
> ```
> context => context.next()
> ```
This line is very close to `context => { context.next(); }` and it's easy to ignore the difference. However, the difference in behavior is quite significant: the former is OK whereas the latter would resolve the remaining routes twice. Once by explicitly calling `context.next()` and the second time by returning an `undefined` result which causes Vaadin.Router to call `context.next()` again.

Let's use `action: () => {}` as a no-op action that should only delegate to the next route.

---

*[test/router/dynamic.redirect.spec.html, line 107 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDfs8vZ3dlMfbdzB2i2:-LDfs8vZ3dlMfbdzB2i3:bs8tsxr) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L107)):*
> ```HTML
>         });
> 
>         it('action that returns an element overrides inactivate for the same route', async() => {
> ```

Would it make sense to allow this use case instead of discarding `inactivate` handlers?
Say, I want to run certain logic when the `/users` subpath becomes inactive. Either one of the configs below should work:

```
router.setRoutes([
  {path: '/', component: 'x-home-view'},
  {
    path: '/users',
    inactivate: onUsersInactivate,
    children: [
      {path: '/', component: 'x-home-view'},
      {path: '/new', component: 'x-home-view'},
      {path: '/:user', component: 'x-home-view'},
    ]
  },
  {path: '/admin', component: 'x-admin-view'}
]);
```
```
router.setRoutes([
  {path: '/', component: 'x-home-view'},
  {path: '/users', action: () => { /* no-op */ }, inactivate: onUsersInactivate},
  {
    path: '/users',
    children: [
      {path: '/', component: 'x-home-view'},
      {path: '/new', component: 'x-home-view'},
      {path: '/:user', component: 'x-home-view'},
    ]
  },
  {path: '/admin', component: 'x-admin-view'}
]);
```

---

*[test/router/dynamic.redirect.spec.html, line 149 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDfwRYoBWAPOK1qraUv:-LDfwRYoBWAPOK1qraUw:b-t5hddo) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L149)):*
> ```HTML
>           router.setRoutes([
>             {path: '/a', component: 'x-home-view', inactivate: () => {
>               inactivateCalled = true;
> ```

How about using a spy (`const inactivate = sinon.spy();`) and then `expect(inactivate).to.have.been.called.once;`?

---

*[test/router/dynamic.redirect.spec.html, line 176 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDfwwrl3TThqdt44vQa:-LDfwwrl3TThqdt44vQb:b-xay2s6) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L176)):*
> ```
> expect(inactivateFunction).to.have.been.called.once;
> expect(inactivateFunction.args.length).to.equal(1);
> ```

Is not it effectively the same assertion? The `spy.args` array should have as many entries as many times the spy has been called.

---

*[test/router/dynamic.redirect.spec.html, line 184 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDg0hXo7CV4LvDdtc3z:-LDg0hXo7CV4LvDdtc4-:bakil9e) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L184)):*
> ```HTML
>         });
> 
>         it('inactivate is not called for same routes in new resolve pass', async() => {
> ```

Let's add a test case that verifies the order in which the inactivation callbacks are called? It should be `[C, B]` in this case.

---

*[test/router/dynamic.redirect.spec.html, line 206 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDg-ENMCpAtP14sWuJk:-LDg-ENMCpAtP14sWuJl:b-xmxrkw) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L206)):*
> ```HTML
>         });
> 
>         it('inactivate that returns rendered component, changes render target and reverts active routes changes', async() => {
> ```

When looking at this and the next test cases now I realize that in many cases it's probably not an expected behavior. When defining an `inactivate()` callback, I would use it as a way to prevent inactivation and keep the content rendered in the previous render pass (`return false`), rather than as a way to return some new content to be rendered when the view is inactivated (`return document.createElement('div')`).

What do you think of reconsidering the spec in this case and changing the supported inactivate callback values to `undefined` and `false`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)*

**Comment by vlukashov** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/router.js, line 145 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDgDpJn1KF8QPTTpWhM:-LDgDpJn1KF8QPTTpWhN:bwxdnx9) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/src/router.js#L145)):*
> ```JavaScript
>   }
> 
>   __isResultNotEmpty(result) {
> ```

This does not need to be a member function, does it? It will save a few bytes by not requiring to append `this.` to call it :)

---

*[src/router.js, line 293 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDgCldmBcGlvJ25RURH:-LDgCldmBcGlvJ25RURI:b-4jo6g2) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/src/router.js#L293)):*
> ```JavaScript
>    */
>   render(pathnameOrContext, shouldUpdateHistory) {
>     this.resolveRoute = context => this.__resolveRoute(context);
> ```

Why is it necessary to set this in every `render()` call?

---

*[src/router.js, line 403 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDgEsia2w9_BluW_Nu2:-LDgEsia2w9_BluW_Nu3:bnyt698) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/src/router.js#L403)):*
> ```JavaScript
>       element.route.redirectFrom = context.from;
>     }
>     element.context = context;
> ```

We already set the `route` property on route web components. It is documented and is a part of the Vaadin.Router public API.
Do you think the `context` property should become a part of the public API as well? From my perspective, there should not be two different properties.

It looks like this property is needed here for internal purposes of Vaadin.Router. If so, how about changing the Resolver class so that its `resolve()` method returns the context object instead of the result of the `resolveRoute()` call (the result is added to the context and returned that way)?

---

*[test/router/dynamic.redirect.spec.html, line 17 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDg1KTBDbQXEjbXGCno:-LDg1KTBDbQXEjbXGCnp:bp7zc9o) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L17)):*
> ```HTML
>       <div></div>
>     </template>
>   </test-fixture>
> ```

Do we actually use the `<a>` element here? It seems that it can be removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)*

**Comment by SomeoneToIgnore** [comment]
Review status: 0 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/router.js, line 145 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDgDpJn1KF8QPTTpWhM:-LDgHQPg9Io1b8XW_bys:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/src/router.js#L145)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

This does not need to be a member function, does it? It will save a few bytes by not requiring to append `this.` to call it :)
</blockquote></details>

Done.

---

*[src/router.js, line 293 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDgCldmBcGlvJ25RURH:-LDgMAxu4dDeb1H77Vgc:bmt389c) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/src/router.js#L293)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Why is it necessary to set this in every `render()` call?
</blockquote></details>

It's not. 
We cannot set it in the constructor, since it's impossible to use `this` in its context.
We cannot have this method non-member, since we need to access and change the Router field.
We cannot have another parameter and pass Router instance there, since it's Resolver who calls the method.

The only way I can think of is to have some sort of boolean flag to check if we've set the method already.
Any better propositions?

---

*[src/router.js, line 403 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDgEsia2w9_BluW_Nu2:-LDgMryw0B4orAAKWLnL:b-v8xwz5) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/src/router.js#L403)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

We already set the `route` property on route web components. It is documented and is a part of the Vaadin.Router public API.
Do you think the `context` property should become a part of the public API as well? From my perspective, there should not be two different properties.

It looks like this property is needed here for internal purposes of Vaadin.Router. If so, how about changing the Resolver class so that its `resolve()` method returns the context object instead of the result of the `resolveRoute()` call (the result is added to the context and returned that way)?
</blockquote></details>

I've chosen this approach since your proposal breaks lots of tests for the resolver.
Would it be better if we "hide" the property under some `_vaadin` prefix?
If not, how about changing this in the different commit, so we don't increase current PR size?

---

*[test/router/dynamic.redirect.spec.html, line 17 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDg1KTBDbQXEjbXGCno:-LDgIGLa8PEk19yoTuwt:b-qksv59) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L17)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Do we actually use the `<a>` element here? It seems that it can be removed.
</blockquote></details>

`test-fixture` is needed since we check what's rendered inside for some tests.
`<a>` element is not needed indeed, removed.Ok

---

*[test/router/dynamic.redirect.spec.html, line 98 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDfuKZV1WiVALhBAUJ_:-LDgJJ4s9w3d-8vhEJo2:b8xk8i9) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L98)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> context => context.next()
> ```
This line is very close to `context => { context.next(); }` and it's easy to ignore the difference. However, the difference in behavior is quite significant: the former is OK whereas the latter would resolve the remaining routes twice. Once by explicitly calling `context.next()` and the second time by returning an `undefined` result which causes Vaadin.Router to call `context.next()` again.

Let's use `action: () => {}` as a no-op action that should only delegate to the next route.
</blockquote></details>

Sure, agree. But I don't get what I need to fix in the file, everything looks correct here :)

---

*[test/router/dynamic.redirect.spec.html, line 149 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDfwRYoBWAPOK1qraUv:-LDgLkGCAwtPAxuG8jeG:b-s7xssa) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L149)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

How about using a spy (`const inactivate = sinon.spy();`) and then `expect(inactivate).to.have.been.called.once;`?
</blockquote></details>

Ah, right, for some reason forgot to remove it.

---

*[test/router/dynamic.redirect.spec.html, line 176 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDfwwrl3TThqdt44vQa:-LDgM1A77YvhXNhgksGy:b-clg4on) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L176)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> expect(inactivateFunction).to.have.been.called.once;
> expect(inactivateFunction.args.length).to.equal(1);
> ```

Is not it effectively the same assertion? The `spy.args` array should have as many entries as many times the spy has been called.
</blockquote></details>

Oh, I see, thanks, removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)*

**Comment by SomeoneToIgnore** [comment]
*[test/router/dynamic.redirect.spec.html, line 206 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDg-ENMCpAtP14sWuJk:-LDgNS1h1dcT96hHbM2A:b-6qvokm) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L206)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

When looking at this and the next test cases now I realize that in many cases it's probably not an expected behavior. When defining an `inactivate()` callback, I would use it as a way to prevent inactivation and keep the content rendered in the previous render pass (`return false`), rather than as a way to return some new content to be rendered when the view is inactivated (`return document.createElement('div')`).

What do you think of reconsidering the spec in this case and changing the supported inactivate callback values to `undefined` and `false`?
</blockquote></details>

I like the idea, it's way less unpredictable.

Might it be better to support `true` instead?
So when a user explicitly returns `true` (and only `true`, not some trueish value), we discard the new resolution?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)*

**Comment by SomeoneToIgnore** [comment]
Review status: 0 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[test/router/dynamic.redirect.spec.html, line 107 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDfs8vZ3dlMfbdzB2i2:-LDgNyrC5T2jg1R5jUHh:by6xjx8) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L107)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Would it make sense to allow this use case instead of discarding `inactivate` handlers?
Say, I want to run certain logic when the `/users` subpath becomes inactive. Either one of the configs below should work:

```
router.setRoutes([
  {path: '/', component: 'x-home-view'},
  {
    path: '/users',
    inactivate: onUsersInactivate,
    children: [
      {path: '/', component: 'x-home-view'},
      {path: '/new', component: 'x-home-view'},
      {path: '/:user', component: 'x-home-view'},
    ]
  },
  {path: '/admin', component: 'x-admin-view'}
]);
```
```
router.setRoutes([
  {path: '/', component: 'x-home-view'},
  {path: '/users', action: () => { /* no-op */ }, inactivate: onUsersInactivate},
  {
    path: '/users',
    children: [
      {path: '/', component: 'x-home-view'},
      {path: '/new', component: 'x-home-view'},
      {path: '/:user', component: 'x-home-view'},
    ]
  },
  {path: '/admin', component: 'x-admin-view'}
]);
```
</blockquote></details>

If we decide to do it this way and keep the action working, we need to add each route to the active ones before preforming anything, including the action.

This will introduce interesting side effects, for instance, for cases when `context.next()` is called, both routes will be added to the active ones, which will result in active chains like `[ '/a', '/a' ]`

This is how current tests will break in this case:



If we decide not to keep the action working, we are, again, loosing a possibility to track user entries with action, which is kind of weird.

IMO, when a user introduces an action to the route that returns something, it should be always executed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)*

**Comment by SomeoneToIgnore** [comment]
*[test/router/dynamic.redirect.spec.html, line 107 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDfs8vZ3dlMfbdzB2i2:-LDgRFdw6uljTy5ZM86Y:b-forej) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L107)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

If we decide to do it this way and keep the action working, we need to add each route to the active ones before preforming anything, including the action.

This will introduce interesting side effects, for instance, for cases when `context.next()` is called, both routes will be added to the active ones, which will result in active chains like `[ '/a', '/a' ]`

This is how current tests will break in this case:



If we decide not to keep the action working, we are, again, loosing a possibility to track user entries with action, which is kind of weird.

IMO, when a user introduces an action to the route that returns something, it should be always executed.

</blockquote></details>

Also this turns our linear property precedence order in a mess: currently we have 
action -> redirect -> inactivate
where items to the left cancel items to the right.

If we make action cancellable by inactivate, we’ll turn that scheme into rock-paper-scissor game, where each element cancels one and is calcellable by the other :)

In order to document such a scheme, we’ll have to describe each possible combination, which is harder and harder for the users to grasp also.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)*

**Comment by SomeoneToIgnore** [comment]
*[src/router.js, line 403 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDgEsia2w9_BluW_Nu2:-LDgTn5f3gMpd1dChAYF:bjy93mp) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/src/router.js#L403)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I've chosen this approach since your proposal breaks lots of tests for the resolver.
Would it be better if we "hide" the property under some `_vaadin` prefix?
If not, how about changing this in the different commit, so we don't increase current PR size?
</blockquote></details>

Sorry, different PR, not commit.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)*

**Comment by vlukashov** [comment]
Review status: 6 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/router.js, line 403 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDgEsia2w9_BluW_Nu2:-LDjJO4I3M8_IWef9dSb:bgviqjc) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/src/router.js#L403)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Sorry, different PR, not commit.
</blockquote></details>

OK. Let's make this in a different PR then.

---

*[test/router/dynamic.redirect.spec.html, line 107 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDfs8vZ3dlMfbdzB2i2:-LDjKe6qENf8bjDsLfyC:b-oc7zx8) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L107)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Also this turns our linear property precedence order in a mess: currently we have 
action -> redirect -> inactivate
where items to the left cancel items to the right.

If we make action cancellable by inactivate, we’ll turn that scheme into rock-paper-scissor game, where each element cancels one and is calcellable by the other :)

In order to document such a scheme, we’ll have to describe each possible combination, which is harder and harder for the users to grasp also.
</blockquote></details>

OK. Thanks for an extended explanation.

---

*[test/router/dynamic.redirect.spec.html, line 206 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDg-ENMCpAtP14sWuJk:-LDjJy2MAMdRpHO4Uygf:bumu5no) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L206)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I like the idea, it's way less unpredictable.

Might it be better to support `true` instead?
So when a user explicitly returns `true` (and only `true`, not some trueish value), we discard the new resolution?
</blockquote></details>

I'd still go with `false` because in my mental model it's like answering a question:

Router: I'm going to inactivate you. What's your reaction?
Route: false!

But no strong opinion on this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)*

**Comment by SomeoneToIgnore** [comment]
*[test/router/dynamic.redirect.spec.html, line 206 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDg-ENMCpAtP14sWuJk:-LDjfwjI5fA6sOCkgvuC:bcqo9d8) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L206)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

I'd still go with `false` because in my mental model it's like answering a question:

Router: I'm going to inactivate you. What's your reaction?
Route: false!

But no strong opinion on this.
</blockquote></details>

Oh, ok, this way it looks way more logical.
Then let's make it `false`, sure.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)*

**Comment by SomeoneToIgnore** [comment]
Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDgR7R65xPQiFD9b1EP:-LDkAo8dDVTV68HzcnP1:bmqi1g1) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Should we add jsdocs describing inactive contract?
</blockquote></details>

Yes we should, done.

---

*[src/router.js, line 293 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDgCldmBcGlvJ25RURH:-LDjnEXB2EuTkQKLNoSS:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/src/router.js#L293)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

It's not. 
We cannot set it in the constructor, since it's impossible to use `this` in its context.
We cannot have this method non-member, since we need to access and change the Router field.
We cannot have another parameter and pass Router instance there, since it's Resolver who calls the method.

The only way I can think of is to have some sort of boolean flag to check if we've set the method already.
Any better propositions?
</blockquote></details>

Done.

---

*[test/router/dynamic.redirect.spec.html, line 98 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDfuKZV1WiVALhBAUJ_:-LDk0jGH0CFLbDHRc_Uh:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L98)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Sure, agree. But I don't get what I need to fix in the file, everything looks correct here :)
</blockquote></details>

Done.

---

*[test/router/dynamic.redirect.spec.html, line 184 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDg0hXo7CV4LvDdtc3z:-LDk0joP7cwclK_SLtpG:b-fa9yoj) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L184)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Let's add a test case that verifies the order in which the inactivation callbacks are called? It should be `[C, B]` in this case.
</blockquote></details>

Oh, thanks, did it in the wrong order, fixed and done.

---

*[test/router/dynamic.redirect.spec.html, line 206 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDg-ENMCpAtP14sWuJk:-LDjjWkb0W_X3IaI1nmN:bkji0pj) ([raw file](https://github.com/vaadin/vaadin-router/blob/028a3cca3a3c5e8717178cff1a9c2e908531f361/test/router/dynamic.redirect.spec.html#L206)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Oh, ok, this way it looks way more logical.
Then let's make it `false`, sure.
</blockquote></details>

Done, for the fallback we need to keep the previous rendered component now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/router.js, line 186 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDkXCfs7ClilpxdrGCu:-LDkXCfs7ClilpxdrGCv:bjan4rt) ([raw file](https://github.com/vaadin/vaadin-router/blob/7c7359c0c78f8793c4e1930e15f19bb6936736ce/src/router.js#L186)):*
> ```JavaScript
>     if (typeof route.component === 'string') {
>       const renderingResult = Router.renderComponent(route.component, context);
>       if (isResultNotEmpty(renderingResult)) {
> ```

BTW can there be a situation when the result is null or undefined here? To me it looks like either HTML element will be created, or the error thrown in case the "component" is incorrect

Not a blocker to me but check if the "else is never called" in the coverage report.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/router.js, line 186 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/126#-LDkXCfs7ClilpxdrGCu:-LDkfoo_2ljSFDX83dO-:b-o419a3) ([raw file](https://github.com/vaadin/vaadin-router/blob/7c7359c0c78f8793c4e1930e15f19bb6936736ce/src/router.js#L186)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW can there be a situation when the result is null or undefined here? To me it looks like either HTML element will be created, or the error thrown in case the "component" is incorrect

Not a blocker to me but check if the "else is never called" in the coverage report.
</blockquote></details>

Right, fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/126)*

**Pull request merged**
