### PR TITLE
Activate all routes.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/139)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
After some consideration, I would like to agree with part of https://github.com/vaadin/vaadin-router/pull/126#issuecomment-392770691 comment about considering both `action` and `inactivate`.

It seems to be more logical (and explicit) if you activate each route that came into each resolve pass.
This also helps when dealing with `onBeforeEnter` and `onBeforeLeave` events by allowing to process `inactivate` in some cases.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/139#-:-LEBfH07Ci73Yi0RRXsB:bs3rzdz)*

**Comment by vlukashov** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[src/router.js, line 96 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/139#-LEKBL9c1Z9u-y3CyU0p:-LEKBL9e59tu7L73jOa-:b-x1p073) ([raw file](https://github.com/vaadin/vaadin-router/blob/83a553ed2a9f86a0d439cf1841ab82fdcbe40153/src/router.js#L96)):*
> ```JavaScript
>     context.cancel = () => ({cancel: true});
> 
>     if (route.path) {
> ```

This test case fails:

```
it('inactivate', async() => {
  const inactivations = [];
  router.setRoutes([
    {
      path: '/',
      inactivate: () => { inactivations.push('L1') },
      children: [
        {
          path: '',
          inactivate: () => { inactivations.push('L2') },
          children: [
            {
              path: 'a',
              inactivate: () => { inactivations.push('L3') },
              component: 'x-users-view'
            }
          ]
        },
      ]
    },
    {path: '/b', component: 'x-home-view'}
  ]);

  await router.render('/a');
  await router.render('/b');

  expect(outlet.children[0].tagName).to.match(/x-home-view/i);
  expect(inactivations[0]).to.equal('L3');
  expect(inactivations[1]).to.equal('L2');
  expect(inactivations[2]).to.equal('L1');
});
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/139)*

**Comment by vlukashov** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/139)*

**Comment by vlukashov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-router/139#-LEQt-wc35MG4cQReR5I:-LETHoUv26iyNH51QYs4:bnfp4nl) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Reworked an approach, merged `chain` branch into this one (thanks for the fix).

Now we just use `context.chain` and store previous context that has the previous chain.
Inactivate now runs in the single place, right after the resolution and rewritten to be asynchronous.

Note: if `context.next()` is called in the action, the corresponding route is not activated, since that's how resolver works.
</blockquote></details>

:lgtm:

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/139#-:-LETHlxd5TuwDocbKaQI:bnfp4nl)*

**Pull request merged**
