### PR TITLE
Improve the same origin link detection

### LINKED ISSUE #87: Improve the same origin href link detection
The current implementation used in click listener lacks some checks in comparison with [iron-location] implementation:
- `window.location.origin` needs to be compared, instead of just checking that anchor href starts with `document.baseURI`, as that doesn't work for subsequent clicks
- evaluating anchor origin needs to be aligned with `_getSameOriginLinkHref` of the `iron-location`

### PR DESCRIPTION
**Pull request by vlukashov**
Improve the same origin check on `<a>` in-app links.

Fixes #87

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/101)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/101)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-router/101#-LD5tLLc6_VfdRq6olQ0:-LD5tLLc6_VfdRq6olQ1:bgoqbrz) (no related file):*
The "should use the CLICK navigation trigger by default" test is failing in IE11 with this PR, can be actually a test flakiness.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/101)*

**Comment by vlukashov** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-router/101#-LD5tLLc6_VfdRq6olQ0:-LD6XOX92JOpju3wdSjj:b-7ql1td) (no related file):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

The "should use the CLICK navigation trigger by default" test is failing in IE11 with this PR, can be actually a test flakiness.
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/101)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/101)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/101)*

**Comment by web-padawan** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/101)*

**Pull request merged**
