### PR TITLE
Ensure resolved chain matches initial pathname

### LINKED ISSUE #205: Fallback routes do not work when using nested routes with parent layouts
A router with the config below does not render the "not found" view for the `/non-existent` path. It should.

```
router.setRoutes([
  {path: '/', component: 'x-app-layout', children: [
    {path: '/billing', component: 'x-billing-view'},
  ]},
  {path: '(.*)', component: 'x-not-found-view'},
]);
```

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #205

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/215)

### CODE REVIEW

**Comment by vlukashov** [comment]
Review status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @web-padawan)

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-router/215#-LGTUhAb3u0qZrEAtVZw:-LGTUhAb3u0qZrEAtVZx:b-vduxp8) (no related file):*
Should the tests for `matchRoute` / `resolver` be updated to verify that the path calculations work in all cases?

---

*[src/router.js, line 369 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/215#-LGTTymr411tw1r3VgBh:-LGTTymr411tw1r3VgBi:ber0qzk) ([raw file](https://github.com/vaadin/vaadin-router/blob/e2187cf1989e13bfcdabd0e1ef55e803902c3614/src/router.js#L369)):*
> ```
> const lastMatched = chain[chain.length - 1].__matchedPath;
> ```
If you are only interested in the matched path for the last route in the chain, would it work if that path is stored in the context, not in the route objects?

---

*[src/resolver/resolver.js, line 42 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/215#-LGTTFCxDpd1RfntiIu1:-LGTTFCxDpd1RfntiIu2:b-dqel8d) ([raw file](https://github.com/vaadin/vaadin-router/blob/e2187cf1989e13bfcdabd0e1ef55e803902c3614/src/resolver/resolver.js#L42)):*
> ```JavaScript
>   if (newRoute && !newRoute.__synthetic) {
>     if (shouldDiscardOldChain(context.chain, newRoute)) {
>       newRoute.__matchedPath = matchedPath;
> ```

Would this mean that every concurrent resolve pass will be modifying the same route objects? How is this protected against concurrent modifications?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/215)*

**Comment by vlukashov** [comment]
Review status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @web-padawan)

---

*[src/router.js, line 383 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/215#-LGU3e2r2ZW_9qx6khXT:-LGU3e2r2ZW_9qx6khXU:b-tq96e2) ([raw file](https://github.com/vaadin/vaadin-router/blob/2d7ee1a6027df71d390f0111772fa3fc0dfc59fa/src/router.js#L383)):*
> ```JavaScript
>           .then(nextContext => {
>             if (nextContext === null) {
>               if (amendedContext.pathname !== amendedContext.__matchedPath) {
> ```

This test case seems to fail:
```
it('should match routes with trailing slashes', async() => {
  router.setRoutes([
    {path: '/', component: 'x-a'},
    {path: '/child', component: 'x-b', children: [
      {path: '/page/', component: 'x-c'}
    ]},
  ]);
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/215)*

**Comment by web-padawan** [comment]
Review status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @vlukashov and @web-padawan)

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-router/215#-LGTUhAb3u0qZrEAtVZw:-LGU8dIh94UoRBvclYg1:b-896fix) (no related file):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Should the tests for `matchRoute` / `resolver` be updated to verify that the path calculations work in all cases?
</blockquote></details>

Done.

---

*[src/router.js, line 383 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/215#-LGU3e2r2ZW_9qx6khXT:-LGU8Wwt7uIX0VY7-xy6:b45tqy4) ([raw file](https://github.com/vaadin/vaadin-router/blob/2d7ee1a6027df71d390f0111772fa3fc0dfc59fa/src/router.js#L383)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

This test case seems to fail:
```
it('should match routes with trailing slashes', async() => {
  router.setRoutes([
    {path: '/', component: 'x-a'},
    {path: '/child', component: 'x-b', children: [
      {path: '/page/', component: 'x-c'}
    ]},
  ]);
```
</blockquote></details>

Appears to be not related to this PR, also failing on master.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/215)*

**Comment by vlukashov** [comment]
Reviewed 2 of 5 files at r1, 6 of 6 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @vlukashov)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/215)*

**Pull request merged**
