### PR TITLE
Fix the lazy loading demos: resolve demo elements properly

### LINKED ISSUE #113: (demos) the lazy loading demo fails on GitHub pages
When clicking on the 'Lazy load bundle' link in the Lazy Loading demo, the lazy bundle fails to load and there is an error in the browser console:

```
GET https://vaadin.github.io/demo-elements/component-definition.js 404 ()
Path '/lazy' is not properly resolved due to an error. Resolution had failed on route: '/lazy'
```

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #113 

Depends on vlukashov/vaadin-demo-helpers#5

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/117)

### CODE REVIEW

**Comment by vlukashov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[demo/vaadin-router-lazy-loading-demos.html, line 42 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/117#-LDaH2h_2GjaWOFZwGqg:-LDaH2ha2YISwIvYk9cQ:bvyo684) ([raw file](https://github.com/vaadin/vaadin-router/blob/e2ec6feab966467f65af73bb772b9c9f2294d6a0/demo/vaadin-router-lazy-loading-demos.html#L42)):*
> ```
> ${componentsDir}/demo-elements
> ```
naming: how about `${demoComponentsRoot}/component-definition.js`? That way the comment above becomes redundant (the variable name sais is explicitly).

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/117)*

**Comment by web-padawan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/vaadin-router-lazy-loading-demos.html, line 42 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/117#-LDaH2h_2GjaWOFZwGqg:-LDaK3e--fvlfOj8yBEF:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/e2ec6feab966467f65af73bb772b9c9f2294d6a0/demo/vaadin-router-lazy-loading-demos.html#L42)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> ${componentsDir}/demo-elements
> ```
naming: how about `${demoComponentsRoot}/component-definition.js`? That way the comment above becomes redundant (the variable name sais is explicitly).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/117)*

**Comment by vlukashov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/117)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/117)*

**Pull request merged**
