### PR TITLE
Add animated transitions

### LINKED ISSUE #42: Animated transitions
As a developer I want to add CSS animations to route transitions so that I can implement the common app-like visual design patterns for page transitions (like swipes).

Use the [FLIP animation technique](https://aerotwist.com/blog/flip-your-animations/) to ensure smooth 60fps animations.

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #42

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/164)

### CODE REVIEW

**Comment by vlukashov** [comment]
Review status: 0 of 18 files reviewed, 6 unresolved discussions (waiting on @web-padawan)

---

*[demo/vaadin-router-animated-transitions-demos.html, line 39 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LF0ugJu98bZ2MD7SRrD:-LF0ugJu98bZ2MD7SRrE:bafw73n) ([raw file](https://github.com/vaadin/vaadin-router/blob/9db0abc80972e768b46cb19fd58c9ba700ea3d20/demo/vaadin-router-animated-transitions-demos.html#L39)):*
> ```HTML
>           Polymer({
>             is: 'x-fade-out-view',
>             onBeforeLeave: function() {
> ```

Is `onBeforeLeave` really a correct place to start animation? What if navigation is prevented by another component?

---

*[demo/vaadin-router-animated-transitions-demos.html, line 62 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LF0mfv64sfGzJrhSbW3:-LF0mfv64sfGzJrhSbW4:b-91vmel) ([raw file](https://github.com/vaadin/vaadin-router/blob/9db0abc80972e768b46cb19fd58c9ba700ea3d20/demo/vaadin-router-animated-transitions-demos.html#L62)):*
> ```HTML
>         </dom-module>
>         <style>
>           :host {
> ```

Are these styles for the global scope or for a shadow root? Looks like global to me, but why is there `:host` then?

---

*[demo/vaadin-router-animated-transitions-demos.html, line 187 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LF0wfKDElitQ-yf3oe3:-LF0wfKDElitQ-yf3oe4:brfamic) ([raw file](https://github.com/vaadin/vaadin-router/blob/9db0abc80972e768b46cb19fd58c9ba700ea3d20/demo/vaadin-router-animated-transitions-demos.html#L187)):*
> ```HTML
>               path: '/',
>               component: 'x-home-view',
>               animate: (old, now) => RouterTransitions.slideDown(old, now, '0.5s', 'linear')
> ```

It would be awesome if there was a way to define a default transition animation for all views in the app (or for some subset of them) at once. What do you think of making a demo for that use case rather than for individual views?

---

*[demo/vaadin-router-animated-transitions-demos.html, line 192 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LF0xD61Cwi2-YE1QVR2:-LF0xD61Cwi2-YE1QVR3:b8k53yc) ([raw file](https://github.com/vaadin/vaadin-router/blob/9db0abc80972e768b46cb19fd58c9ba700ea3d20/demo/vaadin-router-animated-transitions-demos.html#L192)):*
> ```
> animate: (old, now) => RouterTransitions.fade(old, now, '1s', 'ease-out')
> ```
It would be awesome if the same effect was achievable by `animate: RouterTransitions.fade('1s', 'ease-out')`. What do you think of such an API change?

---

*[src/transitions/animate.js, line 3 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LF0sFDT1Mjud3qANRW2:-LF0sFDT1Mjud3qANRW3:bsk28nh) ([raw file](https://github.com/vaadin/vaadin-router/blob/9db0abc80972e768b46cb19fd58c9ba700ea3d20/src/transitions/animate.js#L3)):*
> ```
> name != 'none'
> ```
Is there a particular reason to use a non-strict equality check?

---

*[test/.eslintrc.json, line 14 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LF0yaIXAj-Q8ZMLKPc_:-LF0yaIXAj-Q8ZMLKPca:b-fkeaay) ([raw file](https://github.com/vaadin/vaadin-router/blob/9db0abc80972e768b46cb19fd58c9ba700ea3d20/test/.eslintrc.json#L14)):*
> ```JSON
>     "gemini": false,
>     "sinon": false,
>     "registerElement": false,
> ```

What do you think of adding this to the `VaadinTestNamespace` instead of creating a new global?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/164)*

**Comment by web-padawan** [comment]
Review status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @web-padawan and @vlukashov)

---

*[demo/vaadin-router-animated-transitions-demos.html, line 39 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LF0ugJu98bZ2MD7SRrD:-LF1crKHBdmRPuPUeodG:bjlocvp) ([raw file](https://github.com/vaadin/vaadin-router/blob/9db0abc80972e768b46cb19fd58c9ba700ea3d20/demo/vaadin-router-animated-transitions-demos.html#L39)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Is `onBeforeLeave` really a correct place to start animation? What if navigation is prevented by another component?
</blockquote></details>

Removed the code to not use this callback at all.

---

*[demo/vaadin-router-animated-transitions-demos.html, line 62 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LF0mfv64sfGzJrhSbW3:-LF1cvWSCn4-nFCu7n5a:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-router/blob/9db0abc80972e768b46cb19fd58c9ba700ea3d20/demo/vaadin-router-animated-transitions-demos.html#L62)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Are these styles for the global scope or for a shadow root? Looks like global to me, but why is there `:host` then?
</blockquote></details>

Removed.

---

*[demo/vaadin-router-animated-transitions-demos.html, line 192 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LF0xD61Cwi2-YE1QVR2:-LF1czJF0Qy3y5--YSKA:b14d6iz) ([raw file](https://github.com/vaadin/vaadin-router/blob/9db0abc80972e768b46cb19fd58c9ba700ea3d20/demo/vaadin-router-animated-transitions-demos.html#L192)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> animate: (old, now) => RouterTransitions.fade(old, now, '1s', 'ease-out')
> ```
It would be awesome if the same effect was achievable by `animate: RouterTransitions.fade('1s', 'ease-out')`. What do you think of such an API change?
</blockquote></details>

Changed the API to not use this.

---

*[src/transitions/animate.js, line 3 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LF0sFDT1Mjud3qANRW2:-LF1d3Pc4gP3EgePXqne:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/9db0abc80972e768b46cb19fd58c9ba700ea3d20/src/transitions/animate.js#L3)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> name != 'none'
> ```
Is there a particular reason to use a non-strict equality check?
</blockquote></details>

Done.

---

*[test/.eslintrc.json, line 14 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LF0yaIXAj-Q8ZMLKPc_:-LF1d48gBcepn8snPNSy:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/9db0abc80972e768b46cb19fd58c9ba700ea3d20/test/.eslintrc.json#L14)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

What do you think of adding this to the `VaadinTestNamespace` instead of creating a new global?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/164)*

**Comment by vlukashov** [comment]
Review status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @vlukashov and @web-padawan)

---

*[demo/vaadin-router-animated-transitions-demos.html, line 11 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LFGQhOL34GPgD-L54y8:-LFGQhOL34GPgD-L54y9:br4y9p4) ([raw file](https://github.com/vaadin/vaadin-router/blob/6ac5a5503a4fbdf493cf8ff3eb7f09db786b68be/demo/vaadin-router-animated-transitions-demos.html#L11)):*
> ```
> The <code>animate</code> property on the route config can be used to establish animated transitions
> ```

This is a short and clear description of what would happen if..., but it does not explain why / when this feature may be useful to start with. Could you please re-word the description so that it starts with a use case.

Something like
"Vaadin.Router allows you to animate transitions between routes. In order to add an animation do blah blah blah, like in the live demo below"

And then (below the demo):
"When the value of the `animate` property is `true`, Vaadin.Router takes the following steps:..."

---

*[src/transitions/animate.js, line 3 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LF0sFDT1Mjud3qANRW2:-LFGRRZV1wMwrT5yDzJ3:b-8rv86f) ([raw file](https://github.com/vaadin/vaadin-router/blob/9db0abc80972e768b46cb19fd58c9ba700ea3d20/src/transitions/animate.js#L3)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

is it done?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/164)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 18 files at r1, 11 of 17 files at r3.
Review status: all files reviewed, 4 unresolved discussions (waiting on @web-padawan and @vlukashov)

---

*[demo/demo-elements/x-image-view.html, line 4 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LFGrP1s-Y285sncg3nF:-LFGrP1s-Y285sncg3nG:b94w0w6) ([raw file](https://github.com/vaadin/vaadin-router/blob/6ac5a5503a4fbdf493cf8ff3eb7f09db786b68be/demo/demo-elements/x-image-view.html#L4)):*
> ```HTML
>   <template preserve-content>
>     <style>
>       host {
> ```

Just curious: why do we need this in every Web Component?

---

*[test/transitions/animate.spec.html, line 30 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LFGuVMF5CkYT1qfrdgt:-LFGuVMF5CkYT1qfrdgu:bpfwac) ([raw file](https://github.com/vaadin/vaadin-router/blob/6ac5a5503a4fbdf493cf8ff3eb7f09db786b68be/test/transitions/animate.spec.html#L30)):*
> ```
> registerElement
> ```

Not sure why do we need to extract it into utils method if it's the only place it's used, but up to you.

> ```
> animate
> ```

Can you point me at the place it gets injected into the test namespace? I cannot find it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/164)*

**Comment by web-padawan** [comment]
Review status: 3 of 10 files reviewed, 4 unresolved discussions (waiting on @SomeoneToIgnore, @vlukashov, and @web-padawan)

---

*[demo/vaadin-router-animated-transitions-demos.html, line 187 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LF0wfKDElitQ-yf3oe3:-LFM2BAy0-A-X8abUkpx:b-hmq1np) ([raw file](https://github.com/vaadin/vaadin-router/blob/9db0abc80972e768b46cb19fd58c9ba700ea3d20/demo/vaadin-router-animated-transitions-demos.html#L187)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

It would be awesome if there was a way to define a default transition animation for all views in the app (or for some subset of them) at once. What do you think of making a demo for that use case rather than for individual views?
</blockquote></details>

Done. Changed the demo to set animate property once.

---

*[src/transitions/animate.js, line 3 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LF0sFDT1Mjud3qANRW2:-LFM2u-k0fEPS9zVcaLv:b6mqk7u) ([raw file](https://github.com/vaadin/vaadin-router/blob/9db0abc80972e768b46cb19fd58c9ba700ea3d20/src/transitions/animate.js#L3)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

is it done?
</blockquote></details>

My bad. Now done.

---

*[test/transitions/animate.spec.html, line 30 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LFGuVMF5CkYT1qfrdgt:-LFM2xNY8Nuv1INhK53y:bin5x0v) ([raw file](https://github.com/vaadin/vaadin-router/blob/6ac5a5503a4fbdf493cf8ff3eb7f09db786b68be/test/transitions/animate.spec.html#L30)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> registerElement
> ```

Not sure why do we need to extract it into utils method if it's the only place it's used, but up to you.

> ```
> animate
> ```

Can you point me at the place it gets injected into the test namespace? I cannot find it.
</blockquote></details>

Done. Will see if I need this method in other tests.

animate is added to test namespace by IIFE bundle created by Rollup.

---

*[demo/demo-elements/x-image-view.html, line 4 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LFGrP1s-Y285sncg3nF:-LFM2U0J07xJrtf5k2Qz:b-g1vbgn) ([raw file](https://github.com/vaadin/vaadin-router/blob/6ac5a5503a4fbdf493cf8ff3eb7f09db786b68be/demo/demo-elements/x-image-view.html#L4)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Just curious: why do we need this in every Web Component?
</blockquote></details>

We don't, in case when default inline is enough. Broken selector BTW, removed. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/164)*

**Comment by vlukashov** [comment]
Please update the demo description and it's LGTM.

---

Reviewed 4 of 17 files at r3, 7 of 10 files at r4, 1 of 1 files at r5.
Review status: all files reviewed, 1 unresolved discussion (waiting on @web-padawan)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/164#-:-LFM7eUrEiGUl7q5igVv:b-jksgai)*

**Comment by web-padawan** [comment]
Review status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @vlukashov and @web-padawan)

---

*[demo/vaadin-router-animated-transitions-demos.html, line 11 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/164#-LFGQhOL34GPgD-L54y8:-LFMUVM7-cIuRvku3VHh:basmxby) ([raw file](https://github.com/vaadin/vaadin-router/blob/6ac5a5503a4fbdf493cf8ff3eb7f09db786b68be/demo/vaadin-router-animated-transitions-demos.html#L11)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> The <code>animate</code> property on the route config can be used to establish animated transitions
> ```

This is a short and clear description of what would happen if..., but it does not explain why / when this feature may be useful to start with. Could you please re-word the description so that it starts with a use case.

Something like
"Vaadin.Router allows you to animate transitions between routes. In order to add an animation do blah blah blah, like in the live demo below"

And then (below the demo):
"When the value of the `animate` property is `true`, Vaadin.Router takes the following steps:..."
</blockquote></details>

Updated. Also, added demo for the object value.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/164)*

**Comment by vlukashov** [comment]
Reviewed 1 of 1 files at r6.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/164)*

**Pull request merged**
