### PR TITLE
Support `onBeforeEnter`, `onBeforeLeave` and `onAfterEnter` navigation lifecycle events.

### LINKED ISSUE #23: Navigation lifecycle events
As a developer I want to define handlers for navigation lifecycle events for a route component:

* before a navigation to the component
* before a navigation away from the component

DoD:

* If a route component has an `onBeforeEnter` method, this method is called (during the resolve pass) every time before a navigation to the component happens.
* If the `onBeforeEnter` method returns something (not `null` nor `undefined`), that return value is used as a resolve pass result for the component (instead of the component itself).
* If a route component has an `onBeforeLeave` method, this method is called (during the resolve pass) every time before a navigation to the component happens.
* If the `onBeforeLeave` method returns something (not `null` nor `undefined`), the resolve pass ends before actually navigating to where it was going to, and that return value is used as the resolve pass result.
* (no demos are in scope for this story because the lifecycle callbacks are demoed in the issues #24 and #25)

The [common DoD](https://github.com/vaadin/vaadin-router/wiki/Definition-of-Done) applies.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Closes #23 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/151)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
As it turned out, `inactivate` feature is not needed for implementation hence it's completely removed.
Since it was the case why we've needed to have a different route by calling `getInvocationPathName`, it and corresponding properties are also removed.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEUQZ7b7mO9GXVfqssF:-LEUQZ7b7mO9GXVfqssG:b2hw7kr) (no related file):*
Where to document the new feature?
We cannot put it into jsdocs of the route, can we?

---

*[test/router/lifecycle-events.spec.html, line 205 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEURaK_9wlGYDC-yRIr:-LEURaK_9wlGYDC-yRIs:b-89a8vd) ([raw file](https://github.com/vaadin/vaadin-router/blob/e4e1f0e249e53e4c1f7932d3dc57ed5a6a7fe47a/test/router/lifecycle-events.spec.html#L205)):*
> ```HTML
>           });
> 
>           expect(XSpy.getLog()).to.deep.equal(['a.action', '*.action']);
> ```

@vlukashov this test was adjusted by me

The original one proposed the following chain: 

```
'a.action',
'*.action',
'*.onBeforeEnter',
'*.connectedCallback',
'*.onAfterEnter',
```

since we render `/` before, it falls to `(.*)` route and renders the route already, hence no extra events.
Seems logical to me.

If we remove `await router.render('/').catch(() => {});` line and run the test, we'll get the:

```
'*.action'
'a.action'
'*.action'
'*.onBeforeEnter'
'*.onBeforeEnter'
'*.connectedCallback'
'*.onAfterEnter'
```

because our router runs `resolve('/')` automatically which is also bad.

If you add 
```
if (pathnameOrContext === '/') {
      return;
    }
```
into `render(pathnameOrContext, shouldUpdateHistory)` method then the expected sequence is displayed.

For now, I have no idea how to avoid double resolution in tests.

---

*[test/router/lifecycle-events.spec.html, line 282 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEURE-0DDFtHLmRt9w9:-LEURE-0DDFtHLmRt9wA:b9higk6) ([raw file](https://github.com/vaadin/vaadin-router/blob/e4e1f0e249e53e4c1f7932d3dc57ed5a6a7fe47a/test/router/lifecycle-events.spec.html#L282)):*
> ```HTML
>           });
> 
>           expect(XSpy.getLog()).to.deep.equal(['route.action']);
> ```

@vlukashov this test is added by me.
In this case we've expected to have 2 actions for some reason when we've drawn this on the blackboard but this does not look logical to me since we do only one resolve pass.

Have adjusted the blackboard.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/151#-:-LEUQgkqDL1lFBDJarN0:b-pih1ux)*

**Comment by vlukashov** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/resolver/resolver.spec.js, line 189 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEcO08mEsuyHgPpXseR:-LEcO08n004JTpQwEq3r:bouajci) ([raw file](https://github.com/vaadin/vaadin-router/blob/e4e1f0e249e53e4c1f7932d3dc57ed5a6a7fe47a/test/resolver/resolver.spec.js#L189)):*
> ```JavaScript
>       const context = await resolver.resolve({pathname: '/a'});
>       expect(context.chain).to.be.an('array').lengthOf(1);
>       expect(context.chain[0].path).to.equal('/a');
> ```

This is ambiguous: which of the two routes should be in the chain?
Let's give routes names and assert on them to make the distinctionchange this to

```
it('context.chain contains the path to the last matched route if context.next() is called', async() => {
  const resolver = new Resolver([
    {path: '/a', name: 'first', action: context => context.next()},
    {path: '/a', name: 'second', action: () => true},
  ]);
  const context = await resolver.resolve({pathname: '/a'});
  expect(context.chain).to.be.an('array').lengthOf(1);
  expect(context.chain[0].name).to.equal('second');
});
```

---

*[test/router/dynamic.redirect.spec.html, line 41 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEcQYLg8GCg9XWMkHsD:-LEcQYLg8GCg9XWMkHsE:b-ltjm80) ([raw file](https://github.com/vaadin/vaadin-router/blob/e4e1f0e249e53e4c1f7932d3dc57ed5a6a7fe47a/test/router/dynamic.redirect.spec.html#L41)):*
> ```HTML
>       });
> 
>       describe('resolver chain and router features', () => {
> ```

What do you think to moving the tests that are resolver-specific, and do not involve much of Router into `resolver.spec.js.`? I've added  separate comments to the two test cases that looks like they could be moved.

---

*[test/router/dynamic.redirect.spec.html, line 51 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEcQevR1kDCca8O6eFp:-LEcQevR1kDCca8O6eFq:b-hnqmcx) ([raw file](https://github.com/vaadin/vaadin-router/blob/e4e1f0e249e53e4c1f7932d3dc57ed5a6a7fe47a/test/router/dynamic.redirect.spec.html#L51)):*
> ```HTML
>         });
> 
>         it('paths with parameters should have each route activated without parameters replaced', async() => {
> ```

This looks resolver-specific. Would it make sense to move it to `resolver.spec.js.`?

---

*[test/router/dynamic.redirect.spec.html, line 83 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEcROvyDW3qvUH1Z1NC:-LEcROvyDW3qvUH1Z1ND:b-3x23gw) ([raw file](https://github.com/vaadin/vaadin-router/blob/e4e1f0e249e53e4c1f7932d3dc57ed5a6a7fe47a/test/router/dynamic.redirect.spec.html#L83)):*
> ```HTML
>         });
> 
>         it('action that uses context.next() does not add an extra active route', async() => {
> ```

This looks resolver-specific. Would it make sense to move it to `resolver.spec.js.`?
Actually, it looks like there is already a test like that there. Is this a duplicate now?

---

*[test/router/dynamic.redirect.spec.html, line 117 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEcRgnW44GiN68ijN6-:-LEcRgnW44GiN68ijN60:brmkqmq) ([raw file](https://github.com/vaadin/vaadin-router/blob/e4e1f0e249e53e4c1f7932d3dc57ed5a6a7fe47a/test/router/dynamic.redirect.spec.html#L117)):*
> ```HTML
>       });
> 
>       describe('onBeforeEnter, onBeforeLeave and onAfterEnter', () => {
> ```

What do you think of moving the test cases related to lifecycle events into `lifecycle-events.spec.html`?

---

*[test/router/dynamic.redirect.spec.html, line 244 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEcUmh580cKm8TsqYXR:-LEcUmh580cKm8TsqYXS:bh6fwhq) ([raw file](https://github.com/vaadin/vaadin-router/blob/e4e1f0e249e53e4c1f7932d3dc57ed5a6a7fe47a/test/router/dynamic.redirect.spec.html#L244)):*
> ```HTML
>         });
> 
>         it('action, onBeforeEnter, onBeforeLeave and onAfterEnter are called in correct order', async() => {
> ```

Is this test case verifying more or less the same as the test cases `(initial) -> /a` and `/a -> /b` from `lifecycle-events.spec.html` (combined)?

---

*[test/router/dynamic.redirect.spec.html, line 290 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEcWNAx47C_7xNOJkZb:-LEcWNAx47C_7xNOJkZc:b-7rkpyh) ([raw file](https://github.com/vaadin/vaadin-router/blob/e4e1f0e249e53e4c1f7932d3dc57ed5a6a7fe47a/test/router/dynamic.redirect.spec.html#L290)):*
> ```HTML
>         });
> 
>         it('when onBeforeEnter returns cancel, resolution is aborted and reverted to the previous state', async() => {
> ```

Should there also be a test for what happens if `onBeforeEnter` returns a redirect?

---

*[test/router/dynamic.redirect.spec.html, line 316 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEcVzyUA_Pemw-vBPAr:-LEcVzyUA_Pemw-vBPAs:bu5dn4h) ([raw file](https://github.com/vaadin/vaadin-router/blob/e4e1f0e249e53e4c1f7932d3dc57ed5a6a7fe47a/test/router/dynamic.redirect.spec.html#L316)):*
> ```HTML
>         });
> 
>         it('when onBeforeEnter, onBeforeLeave and onAfterEnter return any non-cancel value, it is ignored', async() => {
> ```

Can `onAfterEnter` really return anything? I think any return value from that callback should be ignored.
Why can't `onBeforeEnter` return a redirect?

---

*[test/router/lifecycle-events.spec.html, line 57 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEcFPnb8WDd5KvNjrtp:-LEcFPnb8WDd5KvNjrtq:b-d0jbix) ([raw file](https://github.com/vaadin/vaadin-router/blob/e4e1f0e249e53e4c1f7932d3dc57ed5a6a7fe47a/test/router/lifecycle-events.spec.html#L57)):*
> ```
> XSpy.__log.length = [];
> ```
Should be either `XSpy.__log = [];` or `XSpy.__log.length = 0;`. My mistake.

---

*[test/router/lifecycle-events.spec.html, line 205 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEURaK_9wlGYDC-yRIr:-LEcKQ0f4v54hdd6Hkgo:b-m2ucb3) ([raw file](https://github.com/vaadin/vaadin-router/blob/e4e1f0e249e53e4c1f7932d3dc57ed5a6a7fe47a/test/router/lifecycle-events.spec.html#L205)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

@vlukashov this test was adjusted by me

The original one proposed the following chain: 

```
'a.action',
'*.action',
'*.onBeforeEnter',
'*.connectedCallback',
'*.onAfterEnter',
```

since we render `/` before, it falls to `(.*)` route and renders the route already, hence no extra events.
Seems logical to me.

If we remove `await router.render('/').catch(() => {});` line and run the test, we'll get the:

```
'*.action'
'a.action'
'*.action'
'*.onBeforeEnter'
'*.onBeforeEnter'
'*.connectedCallback'
'*.onAfterEnter'
```

because our router runs `resolve('/')` automatically which is also bad.

If you add 
```
if (pathnameOrContext === '/') {
      return;
    }
```
into `render(pathnameOrContext, shouldUpdateHistory)` method then the expected sequence is displayed.

For now, I have no idea how to avoid double resolution in tests.
</blockquote></details>

Indeed, at the moment Router does not have an API to set routes config without triggering a navigation event. We can consider adding this API in the future. For now in tests we could explicitly call the `Resolver.setRoutes` method for that:

```
it('(initial) -> /a/non-existent-path', async() => {
  await router.render('/').catch(() => {});
  XSpy.clearLog();

  // call 'setRoutes' without triggering a navigation event
  Vaadin.Resolver.prototype.setRoutes.call(router, [
    {
      path: '/a',
      action: () => XSpy.log('a.action'),
      children: [
        {path: '/b', action: () => XSpy.log('b.action'), component: 'x-spy'},
      ]
    },
    {path: '(.*)', action: () => XSpy.log('*.action'), component: 'x-spy'},
  ]);
  await router.render('/a/non-existent-path').then(outlet => {
    outlet.children[0].name = '*';
  });

  expect(XSpy.getLog()).to.deep.equal([
    'a.action',
    '*.action',
    '*.onBeforeEnter',
    '*.connectedCallback',
    '*.onAfterEnter',
  ]);
});
```

---

*[test/router/lifecycle-events.spec.html, line 282 at r3](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEURE-0DDFtHLmRt9w9:-LEcKsy86ttXPw9NiPxu:bb6ywmx) ([raw file](https://github.com/vaadin/vaadin-router/blob/e4e1f0e249e53e4c1f7932d3dc57ed5a6a7fe47a/test/router/lifecycle-events.spec.html#L282)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

@vlukashov this test is added by me.
In this case we've expected to have 2 actions for some reason when we've drawn this on the blackboard but this does not look logical to me since we do only one resolve pass.

Have adjusted the blackboard.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/151)*

**Comment by vlukashov** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEdokR70BFJ4AjOvjW1:-LEdokR81UV5QcVaci0Q:b-lz8q63) (no related file):*
I've created  separate branch which contains all changes that I've suggested in the review. Feel free to take some parts from it, or merge it into this PR completely.

Here it is: https://github.com/vaadin/vaadin-router/tree/feature/23-lifecycle-events-review-suggestions

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/151)*

**Comment by vlukashov** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 5 files at r3, 2 of 3 files at r4, 2 of 2 files at r5.
Review status: all files reviewed, 1 unresolved discussion

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/151#-:-LEi3Y9G-HgYU3lgVthO:bnfp4nl)*

**Comment by web-padawan** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @SomeoneToIgnore)

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-router/151#-LEUQZ7b7mO9GXVfqssF:-LEiDW0SDHLAZpparKf5:b-n88omj) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Where to document the new feature?
We cannot put it into jsdocs of the route, can we?
</blockquote></details>

OK to document this in a separate PR, especially #148

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/151)*

**Comment by web-padawan** [comment]
Dismissed @SomeoneToIgnore from a discussion.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/151)*

**Comment by web-padawan** [comment]
Reviewed 1 of 2 files at r2, 1 of 5 files at r3, 2 of 3 files at r4, 2 of 2 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/151)*

**Pull request merged**
