### PR TITLE
chore: update path-to-regexp

### LINKED ISSUE #347: Update path-to-regexp dependency
From:

```
    "path-to-regexp": "2.4.0"
```

To:

```
    "path-to-regexp": "3.0.0"
```

### PR DESCRIPTION
**Pull request by abdonrd**
~Depends on #450~
Fix #347

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/351)

### CODE REVIEW

**Comment by abdonrd** [comment]
Uhm, the tests works for me in local, but fails in Travis. 😕

**Comment by vlukashov** [comment]
The failed test is in the `coverage` test suit, i.e. it's a unit test. On the CI it's run with `npm run test:coverage`. Locally you can run these tests from the console with that same command, or (if you need to debug the test) by opening the `http://127.0.0.1:8000/components/vaadin-router/test/index.coverage.html` URL in the browser when the dev server is started with `npm start`.

From a quick look at the [changes](https://github.com/pillarjs/path-to-regexp/compare/v2.4.0...v3.0.0) made to the path-to-regexp library between the versions 2.4.0 and 3.0.0 it's not immediately clear to me why the test fails. But the failure looks like a legit blocker for vaadin-router to use the new path-to-regexp version without also having a major version change.

**Comment by abdonrd** [comment]
> The failed test is in the `coverage` test suit, i.e. it's a unit test. On the CI it's run with `npm run test:coverage`. Locally you can run these tests from the console with that same command, or (if you need to debug the test) by opening the `http://127.0.0.1:8000/components/vaadin-router/test/index.coverage.html` URL in the browser when the dev server is started with `npm start`.

Yes, when I run `yarn test` it also run `yarn test:coverage` after `wct`.
And both works fine for me locally.

Example with just `yarn test:coverage`:

Screenshot 2019-08-15 at 09 28 26


> From a quick look at the [changes](https://github.com/pillarjs/path-to-regexp/compare/v2.4.0...v3.0.0) made to the path-to-regexp library between the versions 2.4.0 and 3.0.0 it's not immediately clear to me why the test fails. But the failure looks like a legit blocker for vaadin-router to use the new path-to-regexp version without also having a major version change.

Yes, it is quite strange. 😕

**Comment by vlukashov** [comment]
It's a strange situation indeed. On my local machine the test failure is easily reproduced (though I did not do anything special for that). Both from the `npm run test:coverage` command, and in the browser:
image

If you are not able to replicate it in your environment, feel free to leave this PR.

**Comment by vlukashov** [comment]
Hi! Thanks for updating to the new `path-to-regexp` version!

I've looked at the CI build and I see that it fails at the same unit test as with the 2.4.0 to 3.0.0 update. I've opened an issue at the `path-to-regexp` repo to clarify whether or not this is a regression there.

**Comment by abdonrd** [comment]
Now the error is from `vaadin-usage-statistics` types.

**Comment by abdonrd** [comment]
There are any plan to add types to the `vaadin-usage-statistics`? 
Or should we add a declaration file here?

**Comment by abdonrd** [comment]
Friendly ping to @vlukashov about https://github.com/vaadin/vaadin-router/pull/351#issuecomment-567465357

**Comment by vlukashov** [comment]
> There are any plan to add types to the `vaadin-usage-statistics`?
> Or should we add a declaration file here?

As far as I understand, Vaadin is going to add TS type definitions to all its components, eventually. I believe that will include the `vaadin-usage-statistics` module as well.

Until then I would suggest muting the TS compiler in this case (e.g. adding `// @ts-ignore` above the `vaadin-usage-statistics` import). Only if muting the TS compiler is not possible, would I consider providing type definitions for the `vaadin-usage-statistics` module.

On a side note, I find it interesting why do not the master builds fail with the same issue.

**Comment by abdonrd** [comment]
> On a side note, I find it interesting why the master builds do not fail with the same issue.

I will try with a new PR about deps... #450

**Pull request merged**
