### PR TITLE
Allow users to lazy load bundles.

### LINKED ISSUE #20: Route lazy-loading
As a developer I want to lazily load the bundles required to render a route, so that page load times remain low and user experience is good.

DoD:

* the route config JS API supports a `bundle` property. If the property is set for a route, during the resolve pass the router would automatically load the bundle from the given URL before returning the route component
* if the bundle URL ends with `.html` the router loads the bundle as an HTML import
* if the bundle URL ends with `.js` the router loads the bundle as a ES module
* The following snippet should work:

```
router.setRoutes([
  {
    path: '/about',
    bundle: 'bundles/about-bundle.html',
    component: 'x-about-view'
  }, {
    path: '/user',
    bundle: 'bundles/user-view.js',
    component: 'x-user-view'
  }
]);
```
* there is a demo of lazy bundle loading

The [common DoD](https://github.com/vaadin/vaadin-router/wiki/Definition-of-Done) applies.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Closes #20

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/93)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[demo/demo-shell.html, line 2 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LCnVu1660byLWPNf64C:-LCnVu1660byLWPNf64D:byigz0x) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/demo/demo-shell.html#L2)):*
> ```HTML
> <link rel="import" href="../../polymer/polymer.html">
> <link rel="import" href="../../polymer/lib/utils/import-href.html">
> ```

no need for this import, there is `polymer.html` import above which includes this one too

---

*[demo/vaadin-router-lazy-loading-demos.html, line 36 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0SvJqBlW1ePlGanyY:-LD0Se-i5TDHvSh_qt-q:bxh58ct) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/demo/vaadin-router-lazy-loading-demos.html#L36)):*
> ```HTML
>     <h3>Lazy Loading other types of bundles.</h3>
>     <p>Sometimes loading <code>.js</code> and <code>.mjs</code> is not enough.</p>
>     <p>Vaadin.Router allows executing arbitrary tasks via `action` route property,
> ```

note: backticks are not properly highlighted, consider using `<code></code>` here as well

---

*[demo/demo-elements/bundle-script.js, line 1 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0V2cq3bxoSkbfbHuA:-LD0V2cq3bxoSkbfbHuB:bam1gry) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/demo/demo-elements/bundle-script.js#L1)):*
> ```JavaScript
> window.bundle_script_test_variable = 'Hello from bundle script!';
> ```

let's use camelCase as we do elsewhere

---

*[src/router.js, line 9 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0VPeQC1dh5OEbIsxb:-LD0VPeQC1dh5OEbIsxc:b-mla1ie) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/src/router.js#L9)):*
> ```JavaScript
>   const route = context.route;
>   if (route.bundle) {
>     return loadBundle(route.bundle).then(() => processRoute(route, context, params));
> ```

Let's add also `catch` statement here, otherwise we get the error like this:

```
Uncaught (in promise) Event {isTrusted: true, context: {…}, code: 500, type: "error", target: script, …}
```

This is quite confusing from the DX point of view. Also, note the "code" above - 500 is just the default fallback, so I think for not existing file we should have 404 instead.

Let's add the test for this case as well.

---

*[src/utils.js, line 15 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0XZCLBj5ZAq6BP7MY:-LD0XZCLBj5ZAq6BP7MZ:bg0ys1k) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/src/utils.js#L15)):*
> ```JavaScript
>     throw new Error('Route object cannot have both `component` and `action` parameters defined');
>   }
>   if (route.bundle && (typeof route.bundle !== 'string' || !(route.bundle.endsWith('.js') || route.bundle.endsWith('.mjs')))) {
> ```

consider using regexp instead of `endsWith`, e. g. something like this:
```
!route.bundle.match(/.+\.[m]?js$/)
```
this will save a few bytes and remove the need for ES2015 string method for IE11

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/93)*

**Comment by vlukashov** [comment]
Reviewed 6 of 16 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[demo/vaadin-router-lazy-loading-demos.html, line 25 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0ns4h0b-7Q2rhjXxQ:-LD0ns4h0b-7Q2rhjXxR:bvclnti) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/demo/vaadin-router-lazy-loading-demos.html#L25)):*
> ```HTML
>           router.setRoutes([
>             {
>               path: '/',
> ```

It would be nice if lazy loading was easy to spot in the browser dev tools. That is, the default route would be loaded eagerly and a lazy-loaded bundle would be for a non-default view. That way clicking on the link to the second view would trigger lazy loading, which would be easy to see in the dev tools.

Is it feasible to change the demos that way?

---

*[demo/vaadin-router-lazy-loading-demos.html, line 26 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0ok9B9CzMsQsp4pZ_:-LD0ok9B9CzMsQsp4pZa:b-mb03mg) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/demo/vaadin-router-lazy-loading-demos.html#L26)):*
> ```
> 'components/vaadin-router/demo/demo-elements/component-definition.js',
> ```
Would there be any way to make the URL shorter? 

---

*[demo/vaadin-router-lazy-loading-demos.html, line 26 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0opUw6AbhKR5MborG:-LD0opUw6AbhKR5MborH:b-ru4rc0) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/demo/vaadin-router-lazy-loading-demos.html#L26)):*
> ```
> 'components/vaadin-router/demo/demo-elements/component-definition.js'
> ```
Is this file preserved during the docs build process? It needs to stay separate (not part of the docs bundle) to be able to show lazy loading.
(Same for other lazily-loaded files)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/93)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[demo/demo-shell.html, line 2 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LCnVu1660byLWPNf64C:-LD0hNys9Itf-DPo4eyB:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/demo/demo-shell.html#L2)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

no need for this import, there is `polymer.html` import above which includes this one too
</blockquote></details>

Done.

---

*[demo/vaadin-router-lazy-loading-demos.html, line 25 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0ns4h0b-7Q2rhjXxQ:-LD0tyyg42e2m8-VNem4:b-bifhye) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/demo/vaadin-router-lazy-loading-demos.html#L25)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

It would be nice if lazy loading was easy to spot in the browser dev tools. That is, the default route would be loaded eagerly and a lazy-loaded bundle would be for a non-default view. That way clicking on the link to the second view would trigger lazy loading, which would be easy to see in the dev tools.

Is it feasible to change the demos that way?
</blockquote></details>

Makes total sense, adjusted.

---

*[demo/vaadin-router-lazy-loading-demos.html, line 26 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0ok9B9CzMsQsp4pZ_:-LD0vjZKDi1ca_ZXQeKd:b3c2spt) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/demo/vaadin-router-lazy-loading-demos.html#L26)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> 'components/vaadin-router/demo/demo-elements/component-definition.js',
> ```
Would there be any way to make the URL shorter? 
</blockquote></details>

Hm, for some reason relative paths did not work for me before, but now they do.  Most probably caused by non-updated demos.

Adjusted.

---

*[demo/vaadin-router-lazy-loading-demos.html, line 26 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0opUw6AbhKR5MborG:-LD0waHg09NqUcqdX66j:b-5f6oh1) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/demo/vaadin-router-lazy-loading-demos.html#L26)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> 'components/vaadin-router/demo/demo-elements/component-definition.js'
> ```
Is this file preserved during the docs build process? It needs to stay separate (not part of the docs bundle) to be able to show lazy loading.
(Same for other lazily-loaded files)
</blockquote></details>

I can find only two files that contain `'Hello from custom bundle!'` string (same for other bundle files): one in the place I've defined it, the other one in `build/vaadin-router/demo/demo-elements/%name_of_the_file%`:



Judging from this, I would say that the files are preserved and left as separate ones.

---

*[demo/vaadin-router-lazy-loading-demos.html, line 36 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0SvJqBlW1ePlGanyY:-LD0hPHs7xhoDTN2YmbV:bhj92qk) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/demo/vaadin-router-lazy-loading-demos.html#L36)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

note: backticks are not properly highlighted, consider using `<code></code>` here as well
</blockquote></details>

Right, always forget about it somewhere.

Done.

---

*[demo/demo-elements/bundle-script.js, line 1 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0V2cq3bxoSkbfbHuA:-LD0hibYB1e1F2ThH-cu:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/demo/demo-elements/bundle-script.js#L1)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

let's use camelCase as we do elsewhere
</blockquote></details>

Done.

---

*[src/router.js, line 9 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0VPeQC1dh5OEbIsxb:-LD0tRJU8sJ8Bixnrb7w:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/src/router.js#L9)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Let's add also `catch` statement here, otherwise we get the error like this:

```
Uncaught (in promise) Event {isTrusted: true, context: {…}, code: 500, type: "error", target: script, …}
```

This is quite confusing from the DX point of view. Also, note the "code" above - 500 is just the default fallback, so I think for not existing file we should have 404 instead.

Let's add the test for this case as well.
</blockquote></details>

Done.

---

*[src/utils.js, line 15 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0XZCLBj5ZAq6BP7MY:-LD0i5xi3fxDp1CqCVa9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/src/utils.js#L15)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

consider using regexp instead of `endsWith`, e. g. something like this:
```
!route.bundle.match(/.+\.[m]?js$/)
```
this will save a few bytes and remove the need for ES2015 string method for IE11
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/93)*

**Comment by web-padawan** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/93)*

**Comment by SomeoneToIgnore** [comment]
Have updated everything and verified that both demo setups work.

---

Review status: 6 of 24 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/93#-:-LD5pMpH-HNMqTfAQIrs:bbtbuls)*

**Comment by SomeoneToIgnore** [comment]
*[demo/vaadin-router-lazy-loading-demos.html, line 26 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD0opUw6AbhKR5MborG:-LD5pVWmErroWAHFBMZy:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/0caef7d186b13adef66b0cd3125b815520c70ce0/demo/vaadin-router-lazy-loading-demos.html#L26)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I can find only two files that contain `'Hello from custom bundle!'` string (same for other bundle files): one in the place I've defined it, the other one in `build/vaadin-router/demo/demo-elements/%name_of_the_file%`:



Judging from this, I would say that the files are preserved and left as separate ones.

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/93)*

**Comment by web-padawan** [comment]
Reviewed 4 of 11 files at r3, 1 of 1 files at r4, 13 of 16 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/93)*

**Comment by vlukashov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[demo/demo-shell.html, line 19 at r5](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD63k90Ck2W07q-xpYJ:-LD63k90Ck2W07q-xpYK:b122efa) ([raw file](https://github.com/vaadin/vaadin-router/blob/9a4d5298837ae492290d776a55e791b9fa35aaf1/demo/demo-shell.html#L19)):*
> ```HTML
> <link rel="import" href="demo-elements/x-profile-view.html">
> <link rel="import" href="demo-elements/x-user-not-found-view.html">
> <link rel="import" href="demo-elements/x-bundle-test-view.html">
> ```

How about using https://www.polymer-project.org/2.0/docs/api/#function-Polymer.html and removing this html file alltogether?
That way _all_ parts of the the lazy view component would loaded lazily.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/93)*

**Comment by vlukashov** [comment]
Reviewed 3 of 16 files at r1, 2 of 10 files at r2, 4 of 11 files at r3, 1 of 1 files at r4, 13 of 16 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/93)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/demo-shell.html, line 19 at r5](https://reviewable.io/reviews/vaadin/vaadin-router/93#-LD63k90Ck2W07q-xpYJ:-LD6GBiE6_hTp0t-gs-E:b-eap8w2) ([raw file](https://github.com/vaadin/vaadin-router/blob/9a4d5298837ae492290d776a55e791b9fa35aaf1/demo/demo-shell.html#L19)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

How about using https://www.polymer-project.org/2.0/docs/api/#function-Polymer.html and removing this html file alltogether?
That way _all_ parts of the the lazy view component would loaded lazily.
</blockquote></details>

For some reason I thought it is Polymer 3 feature.

Adjusted.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/93)*

**Comment by vlukashov** [comment]
Reviewed 6 of 8 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/93)*

**Pull request merged**
