### PR TITLE
Fixes from the 2nd DX tests session (part 2)

### LINKED ISSUE #153: Run Vaadin.Router DX test scenario 2
Run 5 DX test sessions for the scenario created in #76. Collect the test findings into https://docs.google.com/document/d/1LALD1YznnYs7U-NNYSbbOJu8P5SJS4jZ0cUHrjHQWJ4

### PR DESCRIPTION
**Pull request by vlukashov**
- highlight `context.cancel()` in the onBeforeLeave demo
- make the dynamic redirect demo shorter
- comment what is router outlet in the first demo
- rename 'lazy loading' demos into 'code splitting'
- highlight the possibility to return a Promise from lifecycle callbacks
- mark 'Route Actions' and 'Navigation Triggers' demos as advanced

Closes #153

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/170)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 11 of 11 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/170)*

**Comment by web-padawan** [comment]
Reviewed 3 of 11 files at r1, 2 of 2 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @vlukashov)

---

*[demo/vaadin-router-demo-shared-styles.html, line 6 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/170#-LFHfUByE0EkhG_d9YxW:-LFHfUByE0EkhG_d9YxX:bntx6b9) ([raw file](https://github.com/vaadin/vaadin-router/blob/fcb352d562df2e798f105275b001c6ccaadc27cc/demo/vaadin-router-demo-shared-styles.html#L6)):*
> ```HTML
>   <template>
>     <style>
>       .note {
> ```

consider using the same styles as used by the Lumo theme:

1) sizes:
https://github.com/vaadin/elements-demo-resources/blob/new-menu-and-styles/common.html#L26

2) colors:
https://github.com/vaadin/vaadin-lumo-styles/blob/40bbd2c92d53e6cce4d81ad9cc918500e8f2c7ac/demo/common.html#L187

You can see it in action on [this page](https://cdn.vaadin.com/vaadin-lumo-styles/1.0.0/demo/customization.html).

---

*[demo/vaadin-router-lifecycle-callbacks-demos.html, line 14 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/170#-LFHeRoa6dwAnYB9u-J1:-LFHeRoa6dwAnYB9u-J2:b-8pkry7) ([raw file](https://github.com/vaadin/vaadin-router/blob/fcb352d562df2e798f105275b001c6ccaadc27cc/demo/vaadin-router-lifecycle-callbacks-demos.html#L14)):*
> ```HTML
>       callbacks</em> allow adding custom logic to any point of it:
>       <ul>
>         <li><b><code>onBeforeEnter(context): Promise | Cancel | Redirect</code></b></li>
> ```

should we mention `void` for all the callbacks for consistency?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/170)*

**Comment by web-padawan** [comment]
Bump docs, then LGTM

---

Reviewed 6 of 11 files at r1, 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/170#-:-LFHt67r4rXy04Y2-AW3:b-wp79j1)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/170#-:-LFHtm57DMvXxKVtCN6H:bnfp4nl)*

**Pull request merged**
