### PR TITLE
Fix action handling.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/116)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-router/116#-LD_voo2CmZu20hDgQPZ:-LD_voo2CmZu20hDgQP_:b-7y3wus) (no related file):*
Need to update docs if I'm the last one to merge.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/116)*

**Comment by web-padawan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/router.js, line 10 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/116#-LD_xUH29eZp6vinbXSp:-LD_xUH29eZp6vinbXSq:b-s5nrcv) ([raw file](https://github.com/vaadin/vaadin-router/blob/c8379277eace37a5d5b15541dcbebc996120efb2/src/router.js#L10)):*
> ```JavaScript
> 
>   const actionResult = processAction(context);
>   if (actionResult !== null && actionResult !== undefined) {
> ```

let's add the test for falsey values similar to this one: https://github.com/vaadin/vaadin-notification/blob/master/test/vaadin-notification-test.html#L143

---

*[src/router.js, line 261 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/116#-LD_wgjU1QMkSyS8y94q:-LD_wgjU1QMkSyS8y94r:b-iwrph7) ([raw file](https://github.com/vaadin/vaadin-router/blob/c8379277eace37a5d5b15541dcbebc996120efb2/src/router.js#L261)):*
> ```JavaScript
>         } else {
>           return Promise.reject(new Error(`Got unexpected resolution result: '${result}' for path '${pathnameOrContext}.` +
>             ' Double check that the action on this route returns an html element.'));
> ```

consider shortening to something like this:
```
Incorrect route resolution result for path '${pathnameOrContext}'. Expected the HTML element, got: '${result}'.
```

---

*[test/router.spec.html, line 704 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/116#-LD_xCm_6JzSv7AHaPAg:-LD_xCm_6JzSv7AHaPAh:b-7v35pw) ([raw file](https://github.com/vaadin/vaadin-router/blob/c8379277eace37a5d5b15541dcbebc996120efb2/test/router.spec.html#L704)):*
> ```HTML
>         if (expectedContents) {
>           const exceptionString = e.message || JSON.stringify(e);
>           if (typeof expectedContents[Symbol.iterator] === 'function') {
> ```

please change this to avoid Symbol usage and for..of loop for IE11

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/116)*

**Comment by SomeoneToIgnore** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-router/116#-LD_voo2CmZu20hDgQPZ:-LDa-Ewf9fX4cJd7r_U3:b-bw8e14) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Need to update docs if I'm the last one to merge.
</blockquote></details>

Updated.

---

*[src/router.js, line 10 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/116#-LD_xUH29eZp6vinbXSp:-LD_zTJXBhJpaYCT8jA9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/c8379277eace37a5d5b15541dcbebc996120efb2/src/router.js#L10)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

let's add the test for falsey values similar to this one: https://github.com/vaadin/vaadin-notification/blob/master/test/vaadin-notification-test.html#L143
</blockquote></details>

Done.

---

*[src/router.js, line 261 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/116#-LD_wgjU1QMkSyS8y94q:-LD_zUDq04Kgucprr-gQ:b-nrnq1u) ([raw file](https://github.com/vaadin/vaadin-router/blob/c8379277eace37a5d5b15541dcbebc996120efb2/src/router.js#L261)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

consider shortening to something like this:
```
Incorrect route resolution result for path '${pathnameOrContext}'. Expected the HTML element, got: '${result}'.
```
</blockquote></details>

Changed, but I would like to explicitly mention that the action is the one that causes it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/116)*

**Comment by SomeoneToIgnore** [comment]
*[test/router.spec.html, line 704 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/116#-LD_xCm_6JzSv7AHaPAg:-LDa-qn4EVc0ySQu0qtq:blcb759) ([raw file](https://github.com/vaadin/vaadin-router/blob/c8379277eace37a5d5b15541dcbebc996120efb2/test/router.spec.html#L704)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

please change this to avoid Symbol usage and for..of loop for IE11
</blockquote></details>

Oh, for some reason, thought that we don't have issues with tests in IE11.
Fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/116)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/116)*

**Pull request merged**
