### PR TITLE
Use click navigation trigger by default

### LINKED ISSUE #88: Use the CLICK navigation trigger by default
As a developer I want to use Vaadin.Router without having to import a use a custom element for in-app links so that I can get up and running quickly.

DoD:
 - the `CLICK` navigation trigger is used along with `POPSTATE` by default
 - the separate `click-navigation-trigger` bundle is removed
 - the docs are updated to say that both `CLICK` and `POPSTATE` are active by default, and include instructions for disabling `CLICK` if a custom in-app link element is used
 - the tests are updated to check that both `CLICK` and `POPSTATE` are active by default
 - the existing demos are updated to **not** include and activate the `CLICK` navigation trigger

The [common DoD](https://github.com/vaadin/vaadin-router/wiki/Definition-of-Done) applies.

### PR DESCRIPTION
**Pull request by web-padawan**
Closes #88 

Note: also incorporates small change in tests, especially the `should update the history state after navigation` test was looking confusing with the existing setup.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/96)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[demo/vaadin-router-navigation-trigger-demos.html, line 70 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/96#-LD1UAGf58J9kLBsTeCb:-LD1UAGg8C-J5nInNGK2:b-t1jxww) ([raw file](https://github.com/vaadin/vaadin-router/blob/58898221eceb4f60776638fbcde04cad9c7cbc18/demo/vaadin-router-navigation-trigger-demos.html#L70)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     <p>Before the <code>CLICK</code> navigation trigger can be used, it needs to
>       be explicitly imported from <code>@vaadin/router/triggers/click</code>.
>       It is in a separate module and can easily be excluded from the production
>       bundle if it is not used (to keep the bundle size smaller).</p>
> ```
</details>


We don't import the trigger in the demos, is this true still? If so, would it make sense to show how to do this once in this particular demo?

---

*[demo/vaadin-router-navigation-trigger-demos.html, line 76 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/96#-LD1UCeU8PDozJvrdTkV:-LD1UCeU8PDozJvrdTkW:b-ub7pkj) ([raw file](https://github.com/vaadin/vaadin-router/blob/58898221eceb4f60776638fbcde04cad9c7cbc18/demo/vaadin-router-navigation-trigger-demos.html#L76)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     <p>If using UMD bundles, the <code>CLICK</code> navigation trigger should be
>       included separately from <code>vaadin-router/dist/umd/click-navigation-trigger.js</code>
>       (it is then available as <code>Vaadin.Router.NavigationTrigger.CLICK</code>).
>     </p>
> ```
</details>


Since we've removed the bundle, is this true still?

---

*[test/router.spec.html, line 419 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/96#-LD1UkZdA42UgKsFdIui:-LD1UkZdA42UgKsFdIuj:b-418dqt) ([raw file](https://github.com/vaadin/vaadin-router/blob/58898221eceb4f60776638fbcde04cad9c7cbc18/test/router.spec.html#L419)):*
> ```HTML
>           });
> 
>           it('should use the CLICK navigation trigger by default', async() => {
> ```

Since `POPSTATE` is also enabled by default, should we also check it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/96)*

**Comment by web-padawan** [comment]
Review status: 7 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/vaadin-router-navigation-trigger-demos.html, line 70 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/96#-LD1UAGf58J9kLBsTeCb:-LD1bIAg4MRczmgjoDFt:bcdfi8u) ([raw file](https://github.com/vaadin/vaadin-router/blob/58898221eceb4f60776638fbcde04cad9c7cbc18/demo/vaadin-router-navigation-trigger-demos.html#L70)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
>     <p>Before the <code>CLICK</code> navigation trigger can be used, it needs to
>       be explicitly imported from <code>@vaadin/router/triggers/click</code>.
>       It is in a separate module and can easily be excluded from the production
>       bundle if it is not used (to keep the bundle size smaller).</p>
> ```

We don't import the trigger in the demos, is this true still? If so, would it make sense to show how to do this once in this particular demo?
</blockquote></details>

We do import it eagerly now. Removed this text. There is a note describing how to build the own bundle in the API docs.

---

*[demo/vaadin-router-navigation-trigger-demos.html, line 76 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/96#-LD1UCeU8PDozJvrdTkV:-LD1bS6vBHHHiFNgV9Rb:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-router/blob/58898221eceb4f60776638fbcde04cad9c7cbc18/demo/vaadin-router-navigation-trigger-demos.html#L76)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
>     <p>If using UMD bundles, the <code>CLICK</code> navigation trigger should be
>       included separately from <code>vaadin-router/dist/umd/click-navigation-trigger.js</code>
>       (it is then available as <code>Vaadin.Router.NavigationTrigger.CLICK</code>).
>     </p>
> ```

Since we've removed the bundle, is this true still?
</blockquote></details>

Removed.

---

*[test/router.spec.html, line 419 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/96#-LD1UkZdA42UgKsFdIui:-LD1bUJF--YU36ggUGUZ:b-6cfywf) ([raw file](https://github.com/vaadin/vaadin-router/blob/58898221eceb4f60776638fbcde04cad9c7cbc18/test/router.spec.html#L419)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Since `POPSTATE` is also enabled by default, should we also check it?
</blockquote></details>

There is already a test for it above in the suite.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/96)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/router.spec.html, line 419 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/96#-LD1UkZdA42UgKsFdIui:-LD1bjHaA7uyQlAmcThN:b-j3ueok) ([raw file](https://github.com/vaadin/vaadin-router/blob/58898221eceb4f60776638fbcde04cad9c7cbc18/test/router.spec.html#L419)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

There is already a test for it above in the suite.
</blockquote></details>

Ah, did nit notice that, sorry.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/96)*

**Comment by vlukashov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[demo/vaadin-router-navigation-trigger-demos.html, line 11 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/96#-LD1a8t4EwxnhPZY0WU2:-LD1a8t509mOzj1GLLcd:b-ek3ln2) ([raw file](https://github.com/vaadin/vaadin-router/blob/58898221eceb4f60776638fbcde04cad9c7cbc18/demo/vaadin-router-navigation-trigger-demos.html#L11)):*
This is a good technical explanation of how things work, but it does not tell why this extra level of complexity is needed. I'd suggest rephrasing the intro to something along these lines:

> There are several events that can trigger in-app navigation with Vaadin.Router: `popstate` events, clicks on `<a>` elements, imperative navigation triggered by JavaScript. In order to make a flexible solution that can be tweaked to particular app needs and remain efficient, Vaadin.Router has a concept of pluggable Navigation Triggers that listen to specific browser events and convert them into the Vaadin.Router navigation events.
> 
> The `@vaadin/router` package comes with ...
> 
> According to the naming convention, ...

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/96)*

**Comment by web-padawan** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/vaadin-router-navigation-trigger-demos.html, line 11 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/96#-LD1a8t4EwxnhPZY0WU2:-LD1f7bUAUEhkGm_uuJC:b-896fix) ([raw file](https://github.com/vaadin/vaadin-router/blob/58898221eceb4f60776638fbcde04cad9c7cbc18/demo/vaadin-router-navigation-trigger-demos.html#L11)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

This is a good technical explanation of how things work, but it does not tell why this extra level of complexity is needed. I'd suggest rephrasing the intro to something along these lines:

> There are several events that can trigger in-app navigation with Vaadin.Router: `popstate` events, clicks on `<a>` elements, imperative navigation triggered by JavaScript. In order to make a flexible solution that can be tweaked to particular app needs and remain efficient, Vaadin.Router has a concept of pluggable Navigation Triggers that listen to specific browser events and convert them into the Vaadin.Router navigation events.
> 
> The `@vaadin/router` package comes with ...
> 
> According to the naming convention, ...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/96)*

**Comment by vlukashov** [comment]
Reviewed 7 of 8 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/96)*

**Pull request merged**
