### PR TITLE
add navigation JavaScript API

### LINKED ISSUE #30: Navigation JS API
As a developer I want to trigger navigation imperatively from JS, and to add custom listeners for navigation events.

DoD:

* Vaadin.Router has a public static `go(pathname)` method that updates the browser URL, triggers a popstate event and calls the router's `render(pathname)` method (returns its result).
* Vaadin.Router dispatches a `vaadin-router:route-changed` event on `window` every time after completing a render pass
 * there is a demo for both features

The [common DoD](https://github.com/vaadin/vaadin-router/wiki/Definition-of-Done) applies.

### PR DESCRIPTION
**Pull request by vlukashov**
- add a static Router.go(path) method
 -- rename the `vaadin-router:navigate` event to `vaadin-router:go` to match the method name.
 - add a `vaadin-router:route-changed` event

Closes #30

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/180)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 10 of 10 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/180)*

**Comment by web-padawan** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @vlukashov)

---

*[demo/vaadin-router-redirect-demos.html, line 151 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/180#-LFMyLs25asYGg4cOcua:-LFMyLs25asYGg4cOcub:bcag4bm) ([raw file](https://github.com/vaadin/vaadin-router/blob/43c95cdccd3207a6a47d4421b36abbd06358bf78/demo/vaadin-router-redirect-demos.html#L151)):*
> ```HTML
>     </vaadin-demo-snippet>
>     <p>
>       NOTE: the same effect can be acheived by dispatching a <code>
> ```

typo: achieved

---

*[src/router.js, line 278 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/180#-LFMvV6DAtdqekoODwp1:-LFMvV6DAtdqekoODwp2:b-ylnlg) ([raw file](https://github.com/vaadin/vaadin-router/blob/43c95cdccd3207a6a47d4421b36abbd06358bf78/src/router.js#L278)):*
> ```JavaScript
>           }
>           this.__removeOutletContent();
>           this.__fireRouteChangedEvent(pathnameOrContext.pathname || pathnameOrContext);
> ```

BTW do we need a separate error event here?
Not a blocker to me, can be added later if needed

---

*[src/router.js, line 524 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/180#-LFMv6_32lJYLfUorO7A:-LFMv6_32lJYLfUorO7B:b98zjqb) ([raw file](https://github.com/vaadin/vaadin-router/blob/43c95cdccd3207a6a47d4421b36abbd06358bf78/src/router.js#L524)):*
> ```JavaScript
>    */
>   subscribe() {
>     window.addEventListener('vaadin-router:go',
> ```

nit: now when the event is shorter, consider writing this in one line maybe?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/180)*

**Comment by vlukashov** [comment]
Review status: 2 of 16 files reviewed, 1 unresolved discussion (waiting on @SomeoneToIgnore and @web-padawan)

---

*[demo/vaadin-router-redirect-demos.html, line 151 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/180#-LFMyLs25asYGg4cOcua:-LFN6zrq5kdgkULUf2wm:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-router/blob/43c95cdccd3207a6a47d4421b36abbd06358bf78/demo/vaadin-router-redirect-demos.html#L151)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

typo: achieved
</blockquote></details>

done

---

*[src/router.js, line 278 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/180#-LFMvV6DAtdqekoODwp1:-LFN71k94PVnId1aWC-A:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-router/blob/43c95cdccd3207a6a47d4421b36abbd06358bf78/src/router.js#L278)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW do we need a separate error event here?
Not a blocker to me, can be added later if needed
</blockquote></details>

done

---

*[src/router.js, line 524 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/180#-LFMv6_32lJYLfUorO7A:-LFN72s7DHqk5p2KwSQl:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-router/blob/43c95cdccd3207a6a47d4421b36abbd06358bf78/src/router.js#L524)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: now when the event is shorter, consider writing this in one line maybe?
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/180)*

**Comment by web-padawan** [comment]
Bump docs then LGTM

---

Reviewed 14 of 14 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/180#-:-LFNAptj6PkQpDM99exe:b-2iu5wp)*

**Comment by web-padawan** [comment]
Reviewed 2 of 10 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/180)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 5 of 5 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/180)*

**Pull request merged**
