### PR TITLE
Catch errors in action executions.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Current `master` bundle size is 5.16KB
This PR makes it as 5.28KB

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/104)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[src/router.js, line 24 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/104#-LD6bCdm3Z1UcOvupWkr:-LD6bCdm3Z1UcOvupWks:b-rtae3n) ([raw file](https://github.com/vaadin/vaadin-router/blob/11a352b3b5b7c954c6cb2b4c22a6c94eae657ffb/src/router.js#L24)):*
> ```JavaScript
>   } else if (typeof route.action === 'function') {
>     try {
>       return route.action(context, params).catch(e => processActionError(route.path, e));
> ```

If I understood @vlukashov correctly, alternative way of doing this would be to replace this line with something like:

`return promisify(route, context, params).catch(e => processActionError(route.path, e));`

where `promisify` is defined as: 
```
async function promisify(route, context, params) {
  return await Promise.resolve(route.action(context, params))
}
```

That did not bring any benefits to me: 

* bundle size bumped to 5.3KB
* even though now I process the errors in one place instead of two, all the code for determining the error cause is still required: with this approach `error` can still be `undefined` or `Error` or `Event` type.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/104)*

**Comment by SomeoneToIgnore** [comment]
*[src/router.js, line 24 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/104#-LD6bCdm3Z1UcOvupWkr:-LD6bvg-E3ucICEOYEjK:bytlgge) ([raw file](https://github.com/vaadin/vaadin-router/blob/11a352b3b5b7c954c6cb2b4c22a6c94eae657ffb/src/router.js#L24)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

If I understood @vlukashov correctly, alternative way of doing this would be to replace this line with something like:

`return promisify(route, context, params).catch(e => processActionError(route.path, e));`

where `promisify` is defined as: 
```
async function promisify(route, context, params) {
  return await Promise.resolve(route.action(context, params))
}
```

That did not bring any benefits to me: 

* bundle size bumped to 5.3KB
* even though now I process the errors in one place instead of two, all the code for determining the error cause is still required: with this approach `error` can still be `undefined` or `Error` or `Event` type.
</blockquote></details>

Additionally, this approach causes `eslint` to fail with 
````
/Users/someonetoignore/Work/vaadin/vaadin-router/src/router.js
  29:7  error  Parsing error: Unexpected token function
```


---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/104)*
<!-- Sent from Reviewable.io -->

**Comment by vlukashov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/router.js, line 10 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/104#-LD6xNvr4Di8Ofc9CDIj:-LD6xNvr4Di8Ofc9CDIk:browfdd) ([raw file](https://github.com/vaadin/vaadin-router/blob/11a352b3b5b7c954c6cb2b4c22a6c94eae657ffb/src/router.js#L10)):*
> ```
> return loadBundle(route.bundle)
>   .catch(() => {
>     throw new Error(`Failed to load bundle '${route.bundle}'`);
> ```

This error handler should probably also mention the route that has caused the error.
How about applying the same error handler both for the `bundle` and for the `action` route properties?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/104)*

**Comment by SomeoneToIgnore** [comment]
*[src/router.js, line 10 at r2](https://reviewable.io/reviews/vaadin/vaadin-router/104#-LD78L4p9QL2XjkJpRO1:-LD78L4qCstAUnZosuco:bquwtpj) ([raw file](https://github.com/vaadin/vaadin-router/blob/2724671af925e8a84143416abde910cd0a1cd6b0/src/router.js#L10)):*
> ```JavaScript
>     return loadBundle(route.bundle)
>       .catch(e => {
>         processRouteError(`load bundle '${route.bundle}'`, route.path, e);
> ```

We can consider partial application here and extract `processRouteError(`load bundle '${route.bundle}'`, route.path)` part.

Not sure if it makes any sense though since the code will be refactored in https://github.com/vaadin/vaadin-router/issues/94

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/104)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-router/104#-LDAss0m4YubRZBKep3F:-LDAss0m4YubRZBKep3G:bdejwm8) (no related file):*
As proposed, an alternative and more generic approach: https://github.com/vaadin/vaadin-router/pull/105

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/104)*

**Comment by SomeoneToIgnore** [comment]
Closing due to better alternative in https://github.com/vaadin/vaadin-router/pull/105

**Pull request closed without merging**
