### PR TITLE
Accept object as a bundle property value, set type to module explicitly

### LINKED ISSUE #202: Bundle property should require specifying the type explicitly
As a developer, I want the router not to make any decisions based on the bundle file extension. Currently, the `module` type is only expected for `.mjs` extension, while the router itself no longer uses it. Instead of that, I want to be able to set the config like this:

```js
{
  path: '/users',
  bundle: {
    path: './users.bundle.js',
    type: 'module'
  }
}
```
So it would be up to developer to decide whether to use ES modules (which also means supporting specific browsers only), or use plain JS scripts.

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #202

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/203)

### CODE REVIEW

**Comment by vlukashov** [comment]
Review status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @web-padawan)

---

*[demo/vaadin-router-code-splitting-demos.html, line 31 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/203#-LG0-aCc5qxSmo36ole5:-LG0-aCc5qxSmo36ole6:b-2aealm) ([raw file](https://github.com/vaadin/vaadin-router/blob/c498826703b23102a6c64f0fb359937d263bb847/demo/vaadin-router-code-splitting-demos.html#L31)):*
> ```
> Support for ES module bundles can be achieved by setting <code>type</cod
> ```
 I suggest to re-phrase this to make the message a bit more clear. Something along the lines of

By default Vaadin.Router loads route bundles as regular JavaScript files (async), but it supports ES module bundles as well. In order to use a ES module as a route bundle, set the `bundle` property to an object with the following structure:

---

*[demo/vaadin-router-code-splitting-demos.html, line 121 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/203#-LG-ysOwArjiUtfHW8_s:-LG-ysOwArjiUtfHW8_t:b-7g4mf3) ([raw file](https://github.com/vaadin/vaadin-router/blob/c498826703b23102a6c64f0fb359937d263bb847/demo/vaadin-router-code-splitting-demos.html#L121)):*
> ```
> the module bundler
> ```
*a* module bundler

---

*[src/utils.js, line 28 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/203#-LG0-KRmA-x3ixSVjdBK:-LG0-KRmA-x3ixSVjdBL:bpq543t) ([raw file](https://github.com/vaadin/vaadin-router/blob/68c60d570b6e9201cec4845beb3ec64f1110dfeb/src/utils.js#L28)):*
> ```JavaScript
>   }
> 
>   if (route.bundle && (!isString(route.bundle) || !route.bundle.match(/.+\.[m]?js$/))) {
> ```

Let's allow `.mjs` anyway. I do not think Vaadin.Router should stop developers from using that extension if they so choose.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/203)*

**Comment by vlukashov** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/203#-:-LG05k5bCe4AMi2Inzed:bg7igkv)*

**Comment by vlukashov** [comment]
Reviewed 7 of 7 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/203)*

**Comment by web-padawan** [comment]
Reviewed 3 of 3 files at r2, 7 of 7 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/203)*

**Pull request merged**
