### PR TITLE
Remove redundant 'params' parameter from action.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/111)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
`vaadin-router-lifecycle-events-demos.html` is not generated in my branch, I suspect it had appeared in the previous PR by mistake.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/111#-:-LDGuoHGDiLuQ-PqFqzg:bqnjlii)*

**Comment by SomeoneToIgnore** [comment]
Is there any benefit of having `resolveRoute.js` file as a standalone one?
Looks like

---







*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/111#-:-LDGyKQ6ANCnSwIHf_82:b-7sczfs)*

**Comment by SomeoneToIgnore** [comment]
*[src/resolver/resolveRoute.js, line 12 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/111#-LDHMEp5CLBJdcE8I3dz:-LDHMZ1P2HEcRnnTjqaQ:b-o419a3) ([raw file](https://github.com/vaadin/vaadin-router/blob/78a83c01a5199d5c8fd3b5feb7f8e03a9d6f669a/src/resolver/resolveRoute.js#L12)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> context.route.action(context, context.params);
> ```
`context.route.action(context);` should be enough, right?
</blockquote></details>

Right, fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/111)*

**Comment by vlukashov** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/111)*

**Pull request merged**
