### PR TITLE
Log route path if error is uncaught.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/105)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Cannot use `log.error` here since plenty of tests start to fail because if this error logged.

Should we think about providing a way to turn this log message off?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/105#-:-LDAt0Lq7AxBv1PPFehB:b7wi3yi)*

**Comment by SomeoneToIgnore** [comment]
Also decided to leave `throw new Error(`Failed to load bundle '${route.bundle}'`);` in `router.js` as is since it's very easy to show that specific information.

---







*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/105#-:-LDAtysD60TamSLlbLRl:b-ssupls)*

**Comment by vlukashov** [comment]
I'd say that configurable logging is something for the future, not necessary to add it now.


I'd also remove the `Failed to load bundle '${route.bundle}'` part, since it essentially repeats the same info what the browser logs to the console.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/resolver/resolver.js, line 145 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/105#-LDB-liiA-DapRRTp_4V:-LDB-liiA-DapRRTp_4W:bgwkzwg) ([raw file](https://github.com/vaadin/vaadin-router/blob/f650ae20072fa673d783b287cd56cc7f7b511fed/src/resolver/resolver.js#L145)):*
> ```JavaScript
>       .then(() => next(true, this.root))
>       .catch((error) => {
>         const errorMessage = `Route with path '${currentContext.pathname}' is not properly resolved due to an error.`;
> ```

Let's add the failed route (`currentContext.route.path`) to the message.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/105#-:-LDB02dyDhIrQvFLmhOI:buo0tyb)*

**Comment by vlukashov** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/105)*

**Pull request merged**
