### PR TITLE
remove build-specific Vaadin.Router import from demo snippets

### PR DESCRIPTION
**Pull request by vlukashov**
- replace it with a comment showing both import and UMD options

Related to #67

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/213)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @vlukashov)

---

*[demo/vaadin-router-getting-started-demos.html, line 54 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/213#-LGAiZcJ4TKQZycI8OJD:-LGAiZcJ4TKQZycI8OJE:b-pdmgwp) ([raw file](https://github.com/vaadin/vaadin-router/blob/ee7b812010d83e3a82a7ba4154fdc732605e32f2/demo/vaadin-router-getting-started-demos.html#L54)):*
> ```HTML
> 
>         <script>
>           // import {Router} from '@vaadin/router' / var Router = Vaadin.Router
> ```

consider making uncommented line a valid JS:

```js
 // import {Router} from '@vaadin/router' // for vaadin-router.umd.js: var Router = Vaadin.Router;
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/213)*

**Comment by vlukashov** [comment]
Review status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @web-padawan and @vlukashov)

---

*[demo/vaadin-router-getting-started-demos.html, line 54 at r1](https://reviewable.io/reviews/vaadin/vaadin-router/213#-LGAiZcJ4TKQZycI8OJD:-LGAkgMi7zA7kkxANn9J:b-hea7yv) ([raw file](https://github.com/vaadin/vaadin-router/blob/ee7b812010d83e3a82a7ba4154fdc732605e32f2/demo/vaadin-router-getting-started-demos.html#L54)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

consider making uncommented line a valid JS:

```js
 // import {Router} from '@vaadin/router' // for vaadin-router.umd.js: var Router = Vaadin.Router;
```
</blockquote></details>

How about this one?
```
// import {Router} from '@vaadin/router'; // for Webpack / Polymer CLI
// var Router = Vaadin.Router; // for vaadin-router.umd.js
```

It's two lines instead of one (which is a downside), but the lines are shorter and it's enough to uncomment any one of them to make things work.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/213)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/213)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 22 of 22 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-router/213#-:-LGTqetq2gK6WoLgl0e3:bnfp4nl)*

**Pull request merged**
